### ISSUE TITLE
Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by qiao2818** [Eric-Guo/wechat#100]
升级到0.7.6后，仍然出现这样的422
Started POST "/wechat?signature=58af67800383dbb5c2f0ebc20dfb0188aa0cb2a0&timestamp=1457948002&nonce=1731260316"

Processing by WechatsController#create as */*

Parameters: {"signature"=>"58af67800383dbb5c2f0ebc20dfb0188aa0cb2a0", "timestamp"=>"1457948002", "nonce"=>"1731260316"}

Can't verify CSRF token authenticity

Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)

请问如何解决？

**Comment by qiao2818** [comment]
WechatsController < ApplicationController
这样就会422

WechatsController < ActionController::Base
这样就没事

**Comment by Eric-Guo** [comment]
可能是这个问题，已经有PR了，新版本过两天发，现在在做oauth2，不方便发新版本。
https://github.com/Eric-Guo/wechat/pull/97

**Comment by Eric-Guo** [comment]
v0.7.7已经发布，应该已经修复了这个问题，这个Issue暂时先关了，有问题可以继续开这个issue。
