### ISSUE TITLE
wechat_oauth2 取不到 openid

### ISSUE THREAD

**Issue by iuhoay** [Eric-Guo/wechat#103]
```ruby
class CartController < ActionController::Base
  wechat_api
  def index
    wechat_oauth2 do |openid|
      @current_user = User.find_by(wechat_openid: openid)
      @articles = @current_user.articles
    end
  end
end
```

同样上面一段代码，微信回调也成功了，就是取 openid，会有哪些原因呢
用的 master 版本

**Comment by iuhoay** [comment]
问题出在这里
https://github.com/Eric-Guo/wechat/blob/master/lib/wechat/controller_api.rb#L36

params[:state] = ''
wechat.jsapi_ticket.oauth2_state = nil
cookies[:we_openid] = ''

一直去不到

**Comment by Eric-Guo** [comment]
今天靠你调了，周日之前没时间看。。

**Comment by Eric-Guo** [comment]
确认一下[jsapi_ticket](https://github.com/Eric-Guo/wechat/blob/master/README-CN.md#rails-全局配置)配置了？暂时无法复现你这个问题。

**Comment by Eric-Guo** [comment]
0.7.9发布，已经包括了这个修正。

**Comment by TangMonk** [comment]
0.7.11还是偶尔会有这个问题

**Comment by Eric-Guo** [comment]
删除存储jsapi ticket和token的临时文件，然后重新获取，应该不会出现这个问题了，至少这部分代码是仔细Review过的。
