### ISSUE TITLE
在ApplicationController中使用wechat_api，然后调用 wechat_config_js 出错 

### ISSUE THREAD

**Issue by sunny0425** [Eric-Guo/wechat#104]
undefined method `trusted_domain_fullname' for Wechat::HomeController:Class

**Comment by Eric-Guo** [comment]
你需要在HomeController里面呼叫[`wechat_api`](https://github.com/Eric-Guo/wechat/blob/master/README-CN.md#wechat_api---rails-controller-wechat-api)或者` wechat_responder`申明方法？

**Comment by Eric-Guo** [comment]
可以参考[wechat-starter PR9](https://github.com/goofansu/wechat-starter/pull/9)这个修改，想了想还是必须显式申明wechat_api，为了支持一个应用跑多账号也是拼了！

**Comment by sunny0425** [comment]
谢谢，已经明白了。之前把它写在了父controller里面，所以不起作用。

**Comment by Eric-Guo** [comment]
是的，我承认这个是一个限制，其实应该修掉的。。

**Comment by TangMonk** [comment]
同样遇到了这个问题，夫controller定义的wechat_responder, 在子controller里面调用wechat_config_js报错:

```
undefined method `jsapi_ticket' for nil:NilClass
```

**Comment by Eric-Guo** [comment]
如果只是使用wechat_config_js，其实加入wechat_api即可。

**Comment by Eric-Guo** [comment]
现在这个限制去掉了，同样允许wechat_api写在父controller中了。
