### ISSUE TITLE
How to use redis token store ?

### ISSUE THREAD

**Issue by TangMonk** [Eric-Guo/wechat#108]
Thanks for your work, 

But I cannot see the configuration in document. I only using the generator to generate `config/initializers/wechat_redis_store.rb`, But it still store token to local file.

**Comment by TangMonk** [comment]
I figure it out, just remove `access_token` and `jsapi_ticket` in yml file.

But I have an another question: "Why not using TTL key in redis to expire access_token and jsapi_ticket"

**Comment by Eric-Guo** [comment]
Because TTL key is controlled by Tencent server instead of wechat gem

**Comment by TangMonk** [comment]
@Eric-Guo , Thanks for your reply.
