### ISSUE TITLE
建议完善 README

### ISSUE THREAD

**Issue by sg552** [Eric-Guo/wechat#11]
hi , 
  gem 非常好。
  不过有个问题： 对于没有认证过的 订阅号怎么办？ 没有appid, appsecret.. 我知道的很多朋友都是只有 “未认证的订阅号”. 
如果这两样没有的话，可以使用这个GEM吗？ 

  谢谢
思维

**Comment by richard-ma** [comment]
@sg552 从文档来看是可以结合rails使用的，但对于命令行的功能基本不可用，因为未认证的公众号不提供那些接口的授权，这倒不是这个gem的问题。

**Comment by sg552** [comment]
@richard-ma  
谢谢解释... 我最近一直在忙, 忽略了 微信接口, 回头我会参与到相关的fork, commit, pull request 当中. 

.

**Comment by feitian124** [comment]
微信不同类型公众号权限不同, 具体请参看 
http://mp.weixin.qq.com/wiki/7/2d301d4b757dedc333b9a9854b457b47.html
然后对照此 gem 哪些功能可用.
readme 将逐步完善, 此 issue 先关了.
