### ISSUE TITLE
I don't know how to change WECHAT_OAUTH2_COOKIE_DURATION in wechat.yml or .env

### ISSUE THREAD

**Issue by gabrieltong** [Eric-Guo/wechat#111]
`self.oauth2_cookie_duration = opts[:oauth2_cookie_duration] || Wechat.config.oauth2_cookie_duration || 1.hour`
I think `Wechat.config.oauth2_cookie_duration` is read from `wechat.yml` or .env, so it's a string . I think there's a type mistake ,  oauth2_cookie_duration will be sended `from_now` .

**Comment by Eric-Guo** [comment]
Thank you and this is another bug, 0.7.13 fix it.
