### ISSUE TITLE
多个微信号配置

### ISSUE THREAD

**Issue by yingce** [Eric-Guo/wechat#118]
我们有一个业务需要用不同的微信号给用户发信息， 怎么像controller一样 使用 wechat_responder来设定f好当前的Wechat? 如果是直接修改Wechat.config.appid可取么？Token怎么处理？

**Comment by Eric-Guo** [comment]
在controller这边设定好了之后，你在controller这边使用wechat.sent_message就会使用同这个controller绑定的微信号给用户发消息。

**Comment by yingce** [comment]
我发信息的会是后台Job这样发送

**Comment by Eric-Guo** [comment]
目前没有考虑这个场景，需要将load_controller_wechat和ApiLoader.with两个方法合并后才能支持形如Wechat.api(appid: 'my_appid', secret: 'my_secret', token: 'my_token')这样的后台Job显示调用，欢迎PR。。

**Comment by yingce** [comment]
谢谢啦 我看看

**Comment by Eric-Guo** [comment]
@daggerjames 再次欢迎PR。。

**Comment by xiewenwei** [comment]
刚刚提交了实现这个特性的 PR
https://github.com/Eric-Guo/wechat/pull/150

**Comment by Eric-Guo** [comment]
谢谢，已合并。

**Comment by Eric-Guo** [comment]
0.8.0已经包括的150的内容，多谢vincent！
