### ISSUE TITLE
关于access_token的疑问

### ISSUE THREAD

**Issue by wikimo** [Eric-Guo/wechat#124]
关于access_token，过期后可以去刷新，也可以通过app_id / app_secret去获取，两次刷新间老token仍然有效。Wechat::Token::AccessTokenBase -> token 方法，标记了

Possible two worker running, one worker refresh token, other unaware, so must read every time

先去拿是否已存在的token，而不是先判断是否过期去刷新，这个地方如果逻辑顺序搞错了，是否会引发频繁刷新而陷入一段时间的死循环，谢谢

```
def token
  # Possible two worker running, one worker refresh token, other unaware, so must read every time
  read_token_from_store
  refresh if remain_life_seconds < @random_generator.rand(30..3 * 60)
  access_token
end
```

**Comment by Eric-Guo** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140183&token=&lang=zh_CN

> 中控服务器需要根据这个有效时间**提前**去刷新新access_token。在刷新过程中，中控服务器对外输出的依然是老access_token，此时公众平台后台会保证在刷新短时间内，新老access_token都可用，这保证了第三方业务的平滑过渡；

这个是wechat的核心逻辑，目前的处理方式没有问题，已经是先去拿已经存在的token了。

**Comment by wikimo** [comment]
OK，谢谢，主要想确认下合理性，反过来可能会出问题。
