### ISSUE TITLE
微信JS-SDK的Config注册参数有问题

### ISSUE THREAD

**Issue by daggerjames** [Eric-Guo/wechat#129]
应该是 nonceStr 而不是 noncestr, 见 lib/wechat/ticket/jsapi_base.rb -> signature

参考
http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html#.E6.AD.A5.E9.AA.A4.E4.B8.89.EF.BC.9A.E9.80.9A.E8.BF.87config.E6.8E.A5.E5.8F.A3.E6.B3.A8.E5.85.A5.E6.9D.83.E9.99.90.E9.AA.8C.E8.AF.81.E9.85.8D.E7.BD.AE

**Comment by Eric-Guo** [comment]
感谢指正，好像小写还是可以用，所以这个修正会在下一个release的时候发布。

**Comment by Eric-Guo** [comment]
在生产系统测试了，只有小写可以用，这个改动已经revert。

**Comment by daggerjames** [comment]
sorry 才发现签名中s小写，config中s大写。
