### ISSUE TITLE
params[:state]的比对问题导致无法静默获取openid

### ISSUE THREAD

**Issue by neversion** [Eric-Guo/wechat#131]
```
    def wechat_public_oauth2(oauth2_url)
      if cookies.signed_or_encrypted[:we_openid].blank? && params[:code].blank?
        redirect_to oauth2_url
      elsif cookies.signed_or_encrypted[:we_openid].blank? && params[:code].present? && params[:state] == wechat.jsapi_ticket.oauth2_state #此处params[:state] == ""  而wechat.jsapi_ticket.oauth2_state==nil
        access_info = wechat.web_access_token(params[:code])
        cookies.signed_or_encrypted[:we_openid] = { value: access_info['openid'], expires: self.class.oauth2_cookie_duration.from_now }
        yield access_info['openid'], access_info
      else
        yield cookies.signed_or_encrypted[:we_openid], { 'openid' => cookies.signed_or_encrypted[:we_openid] }
      end
    end
```

如上代码注释，是否应该在 params[:state] == wechat.jsapi_ticket.oauth2_state 改为 （params[:state] == wechat.jsapi_ticket.oauth2_state || params[:state].blanks? && wechat.jsapi_ticket.oauth2_state.blank?）

**Comment by Eric-Guo** [comment]
oauth2_state会在jsapi_ticket每次刷新时获得新的值，所以wechat_public_oauth2无论如何都会获得oauth2_state。

如果你遇到无法静默获取openid，那应该也只会发生第一次刷新时（此时oauth2_state为空），再刷一次就好了。。

**Comment by neversion** [comment]
如果我对于整个流程的理解有误的话请指正：
只有执行 wechat.jsapi_ticket.ticket之后wechat.jsapi_ticket.oauth2_state才会有值。而ticket只是在需要注入wx_config的时候才被读取。因此如果我单单只需要静默获取openid，不在view中调用wechat_config_js，那wechat.jsapi_ticket.oauth2_state则一直为空。

**Comment by neversion** [comment]
我好像找到原因了，发现本地一直没有access_token及wechat_jsapi_ticket，我手动执行两个refresh之后就正常了。这两个token是在何时第一次请求的？

**Comment by Eric-Guo** [comment]
嗯，这个的确是个问题，如果你静默获取openid的话，不用wechat_config_js，似乎是从来没有机会刷新wechat_jsapi_ticket的，虽然我觉得这场景比较少见，但是我承认两个功能（wechat_config_js/wechat_oauth2）在这里相互依赖了，虽然绝大多数情况，你都会同时使用这两个功能。。

**Comment by neversion** [comment]
经过多次测试发现，基本本地已经存在这两个文件，也经常出现因为wechat.jsapi_ticket.oauth2_state为空导致拿不到openid。可否说明下wechat.jsapi_ticket.oauth2_state值初始化的整个流程？

**Comment by neversion** [comment]
详细看了源代码，流程应该是如下：wx_config_js

**Comment by Eric-Guo** [comment]
我知道你的意思，我想想应该怎么改，其实应该将oauth2_state独立出来。

**Comment by daggerjames** [comment]
这个state的值理论上可以是任意的吧？为什么选取jsapi_ticket.oauth2_state呢？我现在有个需要在授权登录的时候存一个自定义的参数，可以放到State里面么？

**Comment by Eric-Guo** [comment]
state的确可以这么用，但是设计目的实际上是为了安全性，也就是说这个state设计的目的是防止有人冒名顶替的登录。。

这也是wechat gem内置帮你填写的原因，而不是放出来让你自定义的原因。

**Comment by daggerjames** [comment]
关于state静默下面有可能取不到值得问题，我今天也大量出现了。而且我的Redis里面ticket里面state是有值的，但是wechat.jsapi_ticket.oauth2_state取不到。好在不影响结果。毕竟""==""

**Comment by Eric-Guo** [comment]
@daggerjames 这个功能其实发布很久了，如果是大量出现的话，可能是腾讯这边的问题。。

当然，我绝对承认现在的实现有问题，至少初始化oauth2_state和调用的次序反了。

**Comment by Eric-Guo** [comment]
#137 一个修正已经发布到0.7.16版本，可以测试一下。
