### ISSUE TITLE
如何在ActiveJob里面使用wechat_api?

### ISSUE THREAD

**Issue by daggerjames** [Eric-Guo/wechat#132]
因为需要在服务器这边把用户上传的音频文件下载下来，我这边的做法是controller读到media_id后，丢给后台的job去下载。
现在直接在ActiveJob里面无法直接用wechat_api，所以考虑下下版本给ActiveJob也monkey patch一下？

**Comment by Eric-Guo** [comment]
可以直接用Wechat.api，同样可以调用。

**Comment by shenhf** [comment]
非常感谢， Rake task 里面方法一样。
