### ISSUE TITLE
接收视频返回错误

### ISSUE THREAD

**Issue by poppinyunhai** [Eric-Guo/wechat#134]
请问：当我给公众账号发送视频文件的时候，提示我“该公众号暂时无法提供服务，请稍后再试”，是因为我是测试账号没有接收视频的权限还是因为别的？

**Comment by Eric-Guo** [comment]
可能吧，没测过，看[沙盒](http://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index)里面好像没说这个。

**Comment by Eric-Guo** [comment]
@poppinyunhai 现在搞出来了么？
