### ISSUE TITLE
现在的access_token缓存直接存文件，不支持负载均衡吧。

### ISSUE THREAD

**Issue by guange2015** [Eric-Guo/wechat#136]
希望可以把接口透出来，可配。
目前我直接将其指定到Rails.cache了。

```defined?(Rails) ? Rails.cache : File```

**Comment by Eric-Guo** [comment]
已经支持了，cache一样的，直接覆盖默认的read_token/write_token即可。

```
rails g wechat:redis_store
```

**Comment by guange2015** [comment]
赞！！
