### ISSUE TITLE
文档有小问题

### ISSUE THREAD

**Issue by daggerjames** [Eric-Guo/wechat#139]
在 send template_message 里面，直接用命令行读的template.yml 可以以template: 为最外层，但是在code里面，template.yml并不能取最外层。code对应的yml应该直接为
template_id: ...
url: ...
若用相同的template.tml会报错。code里面的不能发送。 rails 4.

建议模板应该一致。

**Comment by Eric-Guo** [comment]
谢谢提醒，能进一步发一个PR帮我修正这个文档错误么？

**Comment by daggerjames** [comment]
@Eric-Guo 好的。我晚点发PR。
