### ISSUE TITLE
any plan for payment intergration

### ISSUE THREAD

**Issue by pynixwang** [Eric-Guo/wechat#141]
每个gem采用各自的配置方式，重复的配置在多帐号开发的时候很容易导致配置不一致。。。

**Comment by Eric-Guo** [comment]
没有计划做支付payment，因为已经有了wx_pay，但愿意接受多账号开发配置的一些PR。@jasl

**Comment by jasl** [comment]
多账号一直支持的！(好吧是呼声太大去年RubyConf结束后加的...

这样用就对了~例如
`WxPay::Service::generate_app_pay_req params, {appid: 'APPID', mch_id: 'MCH_ID', key: 'KEY'}`

**Comment by jasl** [comment]
另外其实我也有考虑过封装下账号实体类，不过我觉得会让大多数简单需求复杂，所以没采用

**Comment by Eric-Guo** [comment]
现在0.8.0在多账号上支持得到较大增强，大家看这个issue可以关了么？
