### ISSUE TITLE
wechat_responder对位置上报消息不解析

### ISSUE THREAD

**Issue by junzhepan** [Eric-Guo/wechat#144]
对于location类型的消息，当成fallback来处理了，其他类型都正确，比如图片、语音。。。

**Comment by Eric-Guo** [comment]
是最新版么？(v0.7.17)

**Comment by junzhepan** [comment]
嗯，昨天用的0.7.16是这样，后来更新到0.7.17还是同样的问题。我的Ruby是2.3.1，Rails是5.0.0.1，跟这有关系吗？

**Comment by Eric-Guo** [comment]
没关系，只是#64 0.6.2的时候改过一次，想确保你不是用的这个版本。。

**Comment by junzhepan** [comment]
你们是不是把[位置消息](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140453&token=&lang=zh_CN)和[获取用户地理位置](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140841&token=&lang=zh_CN)弄混了？

**Comment by Eric-Guo** [comment]
[v0.7.18](https://github.com/Eric-Guo/wechat/releases) 加上了获取用户地理位置的支持，可以用最新版试试？

```ruby
  # 处理地理位置消息
  on :label_location do |request|
    request.reply.text("Label: #{request[:Label]} Location_X: #{request[:Location_X]} Location_Y: #{request[:Location_Y]} Scale: #{request[:Scale]}")
  end 
```

**Comment by junzhepan** [comment]
没问题，tks
