### ISSUE TITLE
回复消息中文乱码问题

### ISSUE THREAD

**Issue by UnclePanda** [Eric-Guo/wechat#148]
我在controller里面加了`# encoding: utf-8`，但是现在我用`request.reply.text`中文消息，在微信里显示的是乱码，请问这个问题怎么解决。

**Comment by Eric-Guo** [comment]
检查encoding_aes_key是否配置错？或者如果是公众号的话，先关掉加密试试？

**Comment by UnclePanda** [comment]
多谢回复。我在测试号下做的，没有加密。我现在回复英文消息是正常的，应该不是加密的问题。

**Comment by UnclePanda** [comment]
问题已解决，发现原因是rails 3 `to_xml`会把中文encode成`&#1234;`字符，后来我们强行转换成中文就好了。rails 4没有这个问题。

**Comment by Eric-Guo** [comment]
wechat gem竟然还支持Rails 3，我真的没想到。。
