### ISSUE TITLE
config/wechat.yml can't be found if it exists in a Rails Engine that uses gem wechat

### ISSUE THREAD

**Issue by brxue** [Eric-Guo/wechat#153]
It looks like the current `wechat` implementation will only find in the Rails Application's `config/wechat.yml` and `~/wechat.yml`?

For Rails Engine, the configuration files under `config/...` will also be parsed by Rails Application, should the Engine's be also considered?

**Comment by Eric-Guo** [comment]
I using Rails Engine daily, but I think such config file should put at application...
