### ISSUE TITLE
公众号发送模板消息或者图文消息的参数

### ISSUE THREAD

**Issue by qiao2818** [Eric-Guo/wechat#158]
在Rails中发送模板消息，或图文消息。

template = YAML.load(File.read(path))

发送图文消息
Wechat.api.custom_message_send Wechat::Message.to(openid).news(template['template'])

发送模板消息
Wechat.api.template_message_send Wechat::Message.to(openid).template(template['template'])

这里在发送的时候，需要传入参数，使不用用户接收到同一模板的消息略有不同，应该如何写？

**Comment by IvanChou** [comment]
这个方法发送模板消息是需要指定用户 openid 的啊
`template = YAML.load(File.read(path)` 之后，template 其实就是一个 Hash，你可以为不同的用户修改里面的内容然后发送给指定的用户
