### ISSUE TITLE
关于access_token问题

### ISSUE THREAD

**Issue by eylu** [Eric-Guo/wechat#16]
微信的 access_token，不是需要动态获取吗，为什么直接写在配置文件config/wechar.yml里？

**Comment by losingle** [comment]
参考以下文档获取access_token（有效期7200秒，开发者必须在自己的服务全局缓存access_token）
http://mp.weixin.qq.com/wiki/15/54ce45d8d30b6bf6758f68d2e95bc627.html

**Comment by xixilive** [comment]
集群环境下可能是需要重新考虑缓存方案

**Comment by feitian124** [comment]
@xixilive @losingle 已经说的比较清楚了
