### ISSUE TITLE
wechat_oauth2 取到的 openid 可能为空

### ISSUE THREAD

**Issue by IvanChou** [Eric-Guo/wechat#160]
最近对项目做了一小点重构，从监控的报错发现了这个问题，频率还不算低

```ruby
wechat_oauth2(scope) do |openid|
  p openid # => nil
end
```

开发环境下没有复现成功，感觉跟微信那边的响应有关，但是没有任何报错信息

不知道有没有其他的盆友也遇到相同的问题

先建个 issue 备忘，然后我去抓 bug 去了 😄

**Comment by IvanChou** [comment]
这个问题是 #131  的延续

```ruby
def wechat_public_oauth2(oauth2_url)
  if cookies.signed_or_encrypted[:we_openid].blank? && params[:code].blank?
    ...
  elsif cookies.signed_or_encrypted[:we_openid].blank? &&
            params[:code].present? &&
            params[:state].to_s == wechat.jsapi_ticket.oauth2_state.to_s
    ...
  else
    ...
  end
```

这段逻辑还有一个很明显的问题， `cookies.signed_or_encrypted[:we_openid]` 为空，`params[:state].to_s != wechat.jsapi_ticket.oauth2_state.to_s`  的时候就会走到 `else` 里面去了

取到的 openid 就是空了

**Comment by IvanChou** [comment]
但是很奇怪，我并没有调用 PublicJsapiTicket 的 ticket 或者 signature 方法
为什么有时候 wechat.jsapi_ticket.oauth2_state 会莫名其妙的有值了，不知道怎么触发的

难道是线程不安全？

**Comment by nykma** [comment]
您好，我这里生产环境经常会发生静默获取openid失败，微信那边给的错误码是 [40029](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433747234&token=&lang=zh_CN)，查了一下[很多人都遇到了这个问题](https://segmentfault.com/q/1010000002739502)，请问这问题和这个issue有关吗？

**Comment by IvanChou** [comment]
没有关系

40029 是因为授权后的 code 已经使用过一次了，微信为了安全考虑不允许一个 code 被重复使用。

我曾经花了不少时间去追踪这类报错的触发原因，因为就 gem 本身的设计来说是不会出现这种情况的，发现大概有下面几种情况：

1. 用户在授权之后，网速略慢，感觉白屏时间有点久了，于是正好在第一次请求返回前刷新了页面
2. 几乎同时收到两个完全一样的授权回调请求，不排除是某些手机某些版本的微信内置浏览的某些行为导致的
3. 还有一种比较神奇，用户授权完成后，几秒钟后另一个 ip 又来请求了同一个 URL， 😂 这个原因我就不瞎猜了

一开始我选择 catch 40029 error，然后让用户重新走一遍静默授权，确实不报错了，世界安静了。
然而当我完成后面的调查后，默默的去把这段错误处理删掉了，还是让它报吧

PS: 如果你真的想要干掉这个报错，并且在乎效率和用户的体验，有一个不错的方法是缓存 web_access_token 的结果，1 min 足矣

**Comment by nykma** [comment]
哇情况好多，感谢你的宝贵经验，我折腾一下……
