### ISSUE TITLE
parse_response(response, as)不支持xml返回

### ISSUE THREAD

**Issue by zhangbin** [Eric-Guo/wechat#167]
调用微信企业红包时，微信的请求参数和返回参数都是xml格式，目前的格式默认为json

微信文档：https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon.php?chapter=13_4&index=3

**Comment by Eric-Guo** [comment]
可以在[content_type上添加一个xml头](https://github.com/Eric-Guo/wechat/blob/master/lib/wechat/http_client.rb#L71)，然后在后面分析处理一下，目前我不在开发微信企业号，你方便提这个功能PR么？

**Comment by zhangbin** [comment]
已经提交
