### ISSUE TITLE
如何返回订阅页面？

### ISSUE THREAD

**Issue by joezhang** [Eric-Guo/wechat#170]
点击菜单进入定义的url页面，期间会执行不同的操作跳转不同的页面，在完成操作之后，请问有什么指令可以关闭所有打开的页面，回到订阅页面？（就如同点击顶部的back和close按钮一样）

**Comment by Eric-Guo** [comment]
你大概需要[wx.closeWindow();](http://mp.weixin.qq.com/wiki/7/1c97470084b73f8e224fe6d9bab1625b.html#.E5.85.B3.E9.97.AD.E5.BD.93.E5.89.8D.E7.BD.91.E9.A1.B5.E7.AA.97.E5.8F.A3.E6.8E.A5.E5.8F.A3)？
