### ISSUE TITLE
failed to get user info after snsapi_login 

### ISSUE THREAD

**Issue by jstdoit** [Eric-Guo/wechat#172]
when  i use `snsapi_login` and then got the openid from wechat, but I cannot access user's info with `wechat.user(openid)`, I just got `48001` errorcode.

Anyone can help me will be goodman.

**Comment by Eric-Guo** [comment]
it's [api privilege](https://github.com/Eric-Guo/wechat#the-api-privilege) problem from Tencent, you account must in verified status, other will return [48001 api not grant error](http://mp.weixin.qq.com/wiki/17/fa4e1434e57290788bde25603fa2fcbd.html).
