### ISSUE TITLE
web_userinfo's web_access_token BEST PRACTICE?

### ISSUE THREAD

**Issue by jstdoit** [Eric-Guo/wechat#173]
I am using `snsapi_login` to authenticate user's account. see, i found the `web_userinfo` method from `api.rb` requiring params named `web_access_token`, also i found that `wechat` gem cache `openid` & `unionid` in the cookie but without `access_token`.

So, when im trying to use `wechat` gem's `web_userinfo`, is there any best practice for how to get the probably `web_access_token` info?

Thanks.

**Comment by Eric-Guo** [comment]
#174，maybe not goo, but at least works, now 0.8.5 contain this PR.
