### ISSUE TITLE
微信支持的群发借口是不是可以考虑支持一下呢？

### ISSUE THREAD

**Issue by wanxsb** [Eric-Guo/wechat#176]
群发给关注的所有用户的接口是否有考虑过支持呢

**Comment by Eric-Guo** [comment]
给个文档链接，我来加。:smile:

**Comment by zero1108** [comment]
https://mp.weixin.qq.com/wiki
消息管理中的发送消息-群发接口

**Comment by jimmy0017** [comment]
https://mp.weixin.qq.com/wiki?action=doc&id=mp1481187827_i0l21&t=0.9411114556868778
这个链接比较好看。

**Comment by Eric-Guo** [comment]
0.8.5已经添加群发消息接口支持。
