### ISSUE TITLE
请问微信用户关注订阅号时，如何才能在controller里面获取到微信用户的昵称等基本信息

### ISSUE THREAD

**Issue by lorbin** [Eric-Guo/wechat#178]
本人对ruby,rails还是太熟悉，还在学习当中，现在利用wechat gem我能做到的是：直接执行命令行wechat user openid已经能拿用户的昵称；微信用户关注订阅号时，会自动回复FromUser字段值过去；微信用户发送信息给订阅号时，可以自动回复信息。

但我想在用户关注订阅号时，就直接拿到该用户的昵称等基本信息，摸索了比较长的时间，试过了问度娘，查看已有issues，看wechat源码（有比较多的看不懂），至今未能解决。

也想过使用OAuth2.0验证接口来获取用户信息，但也未能摸索出完整的方案（不知除了controller以外，还要做哪些配置和操作才能完成拿到用户信息）

所以想在这里请教一下解决方案，最好是可以直接把相关的controller的代码贴一下，谢了

**Comment by jimmy0017** [comment]
你是企业号还是订阅号？是否认证了？很多信息都是需要认证后才提供的。

**Comment by lorbin** [comment]
个人的订阅号，没有认证过，通过命令行可以获取所有微信用户和微信用户个人信息了，现在是想微信用户关注时，自动获取该用户的基本信息

**Comment by Eric-Guo** [comment]
[订阅号必须认证，否者无法获取用户信息](https://github.com/Eric-Guo/wechat/blob/master/README-CN.md#关于接口权限)。
