### ISSUE TITLE
message.rb第68行，如果在多账户的情况下，会导致从默认账户取配置，而不是加载时指定的account

### ISSUE THREAD

**Issue by fxg** [Eric-Guo/wechat#182]
68行：
return nil unless Wechat.config.have_session_class

这一行会导致从defalut账户中读取，我找到问题了，但是不知道怎么修正。

辛苦

**Comment by Eric-Guo** [comment]
你可能需要复写WechatSession的find_or_initialize_session和save_session，比如按照appid存取之类的，这部分写的时候没有考虑到多账户，欢迎PR。。

**Comment by fxg** [comment]
好的，我试试
