### ISSUE TITLE
测试公众服务号 添加接口配置信息失败

### ISSUE THREAD

**Issue by yanchengv** [Eric-Guo/wechat#185]
接口配置信息保存不上，填写url和token，点击保存没有任何反应！但是wechat users可以输出所有关注用户的openids

url: http://1edecedd.ngrok.io/wechat
token: dc823f1d5710be66ae53a735

本地控制台检验signature进行校验响应代码：
```ruby
Started GET "/wechat?signature=fa6ad17e4ffb0354a5efa950fc18f12faa348835&echostr=3906836068556463679&timestamp=1492507185&nonce=915794933" for 103.7.30.106 at 2017-04-18 17:19:47 +0800
Processing by WechatsController#show as */*
  Parameters: {"signature"=>"fa6ad17e4ffb0354a5efa950fc18f12faa348835", "echostr"=>"3906836068556463679", "timestamp"=>"1492507185", "nonce"=>"915794933"}
  Rendering text template
  Rendered text template (0.0ms)
Completed 200 OK in 1ms (Views: 0.4ms | ActiveRecord: 0.0ms)

```

**Comment by yanchengv** [comment]
去掉puma就好了，使用webrick服务器！😌

**Comment by Eric-Guo** [comment]
这不科学。。。不过最近我发现腾讯接口配置的Timeout变严格了，好像超时时间设的很短。

**Comment by fxg** [comment]
是有这个问题，ngrok，还有tunnel.mobi，不管是puma还是thin，都不友好，我现在是用的autossh，暂时没有任何副作用，而且autossh其实是对ssh包了一层，SSH反向连接更靠谱一点。

**Comment by linjunzhu** [comment]
我了个去，真的很不科学， 我也是同样将 puma 替换成了 webrick ，就配置成功了。

**Comment by Davidzhu001** [comment]
+1

**Comment by primaulia** [comment]
Hi all,

Not a Chinese-speaker her, so I hope you guys can reply in English. So I managed to get my rails app to respond to wechat when I test it on the `sandbox` environment.

But when I test it on aliyun server, I don't seem to be able to replicate the response.

**Comment by Eric-Guo** [comment]
Checking `token`, `encoding_aes_key` is correct and Wechat Callback URL matches your Aliyun server, also make sure Aliyun server 80/443 port is accessible, then try again, there is also some [known-issue](https://github.com/Eric-Guo/wechat#known-issues) you can check.

**Comment by primaulia** [comment]
Thanks, will check on it. 

But a follow-up question, can I still run `puma` on my production server? Or do I need to run `webrick` too on my production server?

**Comment by Eric-Guo** [comment]
I running `puma` on all my production server, so it's definitely supported, no need and shouldn't running `webrick` in year 2019
