### ISSUE TITLE
invalid signature while entering new page with tuborlinks on iOS

### ISSUE THREAD

**Issue by imWildCat** [Eric-Guo/wechat#190]
```
Rails: 5.1.1
WeChat: 0.8.8
```

### Expected behaviour

`wechat_config_js` working property in every page.

### Actual behaviour

It said `invalid signature` while jumping from the front page into the second pages.
**Only on real iOS devices**. However, on the simulator (WeChat Web Developer Tool) and Android, it works fine.

**Comment by NaiveCAI** [comment]
I met this problem too 😂, it fucked me two days...

Previously I use link_to xxxxx method: :post to post some data to the url, it works fine.

But when I change it to normal get link, it always config failed invalid signature.

Then I see this issue.

It reminds me of the _*method: :post*_ option, then I add link_to xxxxx method: :get, overwrite the get method.

Then it works..

**Comment by Eric-Guo** [comment]
Fix at #242, version 0.10.3
