### ISSUE TITLE
调用 custom_message_send 发送携带了<a>的消息时，做了 unicode escape

### ISSUE THREAD

**Issue by fogisland** [Eric-Guo/wechat#193]
微信客服消息内可以通过 <a> tag 添加超链接，但是通过 custom_message_send 发送时，由于使用了 to_json 方法，对 < 和 > 做了 unicode escape 处理，形如 \uxxxx。微信那边貌似没有对这种情况做正确处理(?),  导致消息显示异常。

可否在 custom_message_send 内用 JSON.generate 替换 to_json ?

谢谢!

**Comment by Eric-Guo** [comment]
可，你想提PR么？

**Comment by fogisland** [comment]
ok，我提了

**Comment by fogisland** [comment]
之前我是直接把自己的消息 hash 做了 to_json 处理，然后出现了 unicode escape 问题；

看了下这边的 spec, 发现应该用 Wechat::Message 封装的相关接口来发送消息，这样到最后，message.to_json 其实还是调用的 JSON.generate 方法，不会出现上面的问题。

谢谢！
