### ISSUE TITLE
signed_or_encrypted

### ISSUE THREAD

**Issue by a112121788** [Eric-Guo/wechat#195]
rails 3.2.22  can't use "cookies.signed_or_encrypted"

**Comment by Eric-Guo** [comment]
can you upgrade to rails 4? it shouldn't so hard or you may need to do a monkey patch for `ActionDispatch::Cookies`

like:

```ruby
class ActionDispatch::Cookies
  def signed_or_encrypted
    signed
  end
end
```

sorry I haven't Rails 3.22 environment, but a patch is welcome
