### ISSUE TITLE
`check_version_conflict': can't activate json-1.8.6, already activated json-2.0.2

### ISSUE THREAD

**Issue by skji** [Eric-Guo/wechat#200]
When I run wechat command in my project, I got this error.
Here is the 截图。
![jietu20171015-111244](https://user-images.githubusercontent.com/2420990/31581280-539aa324-b12d-11e7-88a8-c2a329c14558.jpg)
![jietu20171015-111021](https://user-images.githubusercontent.com/2420990/31581281-53f6f480-b12d-11e7-90ed-bf27b95f6a89.jpg)

**Comment by Eric-Guo** [comment]
Please running `bundle exec wechat`

**Comment by skji** [comment]
It works! Thank u so much for your help, Eric!
