### ISSUE TITLE
AbstractController::ActionNotFound (The action 'index' could not be found for WechatsController)

### ISSUE THREAD

**Issue by skji** [Eric-Guo/wechat#201]
When I use wechat_responder in wechats_controller, I got this error. I don't know how to fix it.
![jietu20171017-171633](https://user-images.githubusercontent.com/2420990/31656688-015a7730-b2f2-11e7-95d2-f0b54912b7a3.jpg)
![jietu20171017-172315](https://user-images.githubusercontent.com/2420990/31658330-56a17c4e-b2f6-11e7-9268-76bf15f6d615.jpg)

**Comment by Eric-Guo** [comment]
Maybe you need inheriting from `class WechatsController < ActionController::Base`? or you need skip some authorize action coming from devise.

**Comment by skji** [comment]
@Eric-Guo Thank u for your reply. I have tried 'class WechatsController < ActionController::Base', it didn't work. I will try skip some authorize action from devise.

**Comment by skji** [comment]
Finally I fixed this. ` resource :wechat, only: [:show, :create]` in `routes.rb` should be changed to ` resource :wechats, only: [:show, :create]`.

However, ` resource :wechat, only: [:show, :create]` has worked well in my last project, I don't know why it couldn't now.
