### ISSUE TITLE
staging 这个环境下读取不了wechat.yml

### ISSUE THREAD

**Issue by Thomastar** [Eric-Guo/wechat#204]
staging 这个环境下读取不了wechat.yml

**Comment by Eric-Guo** [comment]
wechat.yml里面要加`stage:`开头的配置项，和`development:`类似。

**Comment by Thomastar** [comment]
![_006](https://user-images.githubusercontent.com/17611854/33004606-b22dc10a-cdfc-11e7-9f33-2787c07280ce.png)
