### ISSUE TITLE
with_access_token

### ISSUE THREAD

**Issue by Thomastar** [Eric-Guo/wechat#205]
with_access_token  这个方法是在哪里的？

**Comment by Eric-Guo** [comment]
lib/wechat/api_base.rb:55

**Comment by Thomastar** [comment]
小程序二维码图片放在哪里？

**Comment by Thomastar** [comment]
`		# get home code
		def get_home_code(samll_access_token)
			@url = 'https://api.weixin.qq.com/wxa/'.freeze
			@timeout = 60
			@skip_verify_ssl = true
			@client = HttpClient.new(@url, @timeout, @skip_verify_ssl)
			tmp_file = @client.post('getwxacode', JSON.generate(path: 'page/jxcat/store/index' ), params: {access_token: samll_access_token})
			# save code 
			@wxa_code_pic_path = "#{Rails.root}/client/images/code.jpg"
			FileUtils.mv(tmp_file.path, @wxa_code_pic_path)
		end`

**Comment by Thomastar** [comment]
`		# get home code
		def get_home_code(samll_access_token)
			@url = 'https://api.weixin.qq.com/wxa/'.freeze
			@timeout = 60
			@skip_verify_ssl = true
			@client = HttpClient.new(@url, @timeout, @skip_verify_ssl)
			tmp_file = @client.post('getwxacode', JSON.generate(path: 'page/jxcat/store/index' ), params: {access_token: samll_access_token})
			# save code 
			@wxa_code_pic_path = "#{Rails.root}/client/images/code.jpg"
			FileUtils.mv(tmp_file.path, @wxa_code_pic_path)
		end`

**Comment by Thomastar** [comment]
![image](https://user-images.githubusercontent.com/17611854/33114965-30528f40-cf9a-11e7-8df2-461d9556cdd0.png)

**Comment by Thomastar** [comment]
我自己弄的一个，为什么图片下载是不能打开的。而且是打差的。
![image](https://user-images.githubusercontent.com/17611854/33115016-5379b34a-cf9a-11e7-8cf1-9ba7b1c46308.png)
