### ISSUE TITLE
企业号成员管理中的新增成员功能如何实现？

### ISSUE THREAD

**Issue by shenhf** [Eric-Guo/wechat#206]
Https请求方式: POST

https://qyapi.weixin.qq.com/cgi-bin/user/create?access_token=ACCESS_TOKEN

[开发文档：](http://qydev.weixin.qq.com/wiki/index.php?title=%E7%AE%A1%E7%90%86%E6%88%90%E5%91%98)

**Comment by Eric-Guo** [comment]
v0.9.0开始支持。
