### ISSUE TITLE
开放平台做授权登录，invalid code, hints: [ req_id: je7q.a0244th27 ](40029)

### ISSUE THREAD

**Issue by insub** [Eric-Guo/wechat#208]
申请了开放平台，然后我在做PC端扫码登录的时候，扫码得到微信返回的 code，用 web_access_token 这个 api 去获取 access_token 和 openid 的时候
`Wechat.api.web_access_token(params['code'])`

总是报：
`invalid code, hints: [ req_id: je7q.a0244th27 ](40029)`

这是为什么呢？

如果想做开放平台的Oauth第三方登录什么的，有没有相关的方法支持呢？
文档中 wechat_oauth2 这个方法貌似只适合在微信浏览器里面使用

**Comment by insub** [comment]
已自行解决，谢谢

**Comment by Davidzhu001** [comment]
@insub 请问下如何解决的

**Comment by mozillo** [comment]
> @insub 请问下如何解决的

一般出现invalid code 应该是公众号的ak和sk对应不上 多个公众号记得检查
