### ISSUE TITLE
The action 'create' could not be found for WechatsController

### ISSUE THREAD

**Issue by dannio** [Eric-Guo/wechat#209]
I've set everything up and verified my server on wechat, activated the server and sent my account a message and got this on my server:
````
INFO -- : [c640aa51-09ec-4365-b248-71e66d889609] Started POST "/wechat?signature=xxxxxxxxxxxxxxxxx&timestamp=1513074821&nonce=xxxxxxxxxxxxx&openid=xxxxxxxxxxxxxxxxxxxxxx" for xxx.xxx.xxx.xxx at 2017-12-12 10:33:42 +0000
F, [2017-12-12T10:33:42.057144 #27184] FATAL -- : [c640aa51-09ec-4365-b248-71e66d889609]   
F, [2017-12-12T10:33:42.057237 #27184] FATAL -- : [c640aa51-09ec-4365-b248-71e66d889609] AbstractController::ActionNotFound (The action 'create' could not be found for WechatsController):
````
My controller is like this:

````
    class WechatsController < ApplicationController
  
      skip_before_action :authenticate_user!
      skip_authorization_check
      wechat_responder

      # default text responder when no other match
      on :text do |request, content|
        request.reply.text "echo: #{content}" # Just echo
      end
    end
`````

routes.rb

````
Rails.application.routes.draw do
  resource :wechat, only: [:show, :create]
  devise_for :users
end

````

**Comment by Eric-Guo** [comment]
try to write `class WechatsController < ActionController::Base` to make sure there is no authenticate problem, also make sure setting `wechat.yml` correctly.

If problem continue, please post more complete backtrace (instead of only one line above)

**Comment by dannio** [comment]
changing to ````class WechatsController < ActionController::Base```` worked!

I think it's the devise skip_authentication that's causing the error but I can't be sure why.

Thanks, will work with this for now.
