### ISSUE TITLE
多账号环境下 wechat_api 和 wechat_oauth2 的调用方法

### ISSUE THREAD

**Issue by shenhf** [Eric-Guo/wechat#212]
请问在多账号环境下 在 application_controller.rb 中 如何配置 wechat_api 和 wechat_oauth2 ？
`
wechat_api account: params[:account].to_sym
`
是无法获取 params 参数的

**Comment by Eric-Guo** [comment]
可以看看 #150，应该只能在yml文件里面配

**Comment by shenhf** [comment]
谢谢回复。 wechat.yml 是配置了多账号的，现在的问题是 controller 怎么去自适应来自不同账号的请求？

**Comment by Eric-Guo** [comment]
设计的时候没有考虑，应该还是要在controller类中声明wechat_api才行。具体可以看`lib/action_controller/wechat_responder.rb`部分实现。

**Comment by shenhf** [comment]
wechat_api 只能接受静态变量
`
wechat_api account:  :acc1
`
无法读取 params，就无法实现多账号应用

 wechat_api account: params[:account].to_sym

**Comment by Eric-Guo** [comment]
params[:account]中的值在yml有不会导致出错吧。。

**Comment by adamshen** [comment]
wechat_api是class_level下的dsl，params是instance_level下的方法，肯定无法读取啊。目前的代码逻辑在使用dsl的情况下，是不支持单个controller处理多个公众号请求的。如果要实现的话，可以使用Wechat.api取得client对象去做认证，然后再实现自己的show和create action。目前我是这样做的，不知道还没有更好的方法。

**Comment by shenhf** [comment]
建议还是要从整体架构上来考虑多账号的处理。建议通过数据表来管理多账号。@Eric
