### ISSUE TITLE
请问如何忽略 Wechat.api.template_message_send 抛出的 500 错误？

### ISSUE THREAD

**Issue by insub** [Eric-Guo/wechat#214]
在使用 Wechat.api 发送模板消息时，如果对方并未关注公众号，那么微信会返回 43004 。这时候 Wechat 会抛出一个 500 错误，然后随后的业务流程也会被中断。
问题是，支付通知之类的，向未关注公众号的 openid 发送模板消息是一个大概率事件

请问，有没有什么办法来忽略掉这个 43004 ，不要抛出 500 错误？
谢谢

**Comment by Eric-Guo** [comment]
可以在lib/wechat/http_client.rb:L60这里忽略掉，有没有兴趣提个PR？

**Comment by insub** [comment]
@Eric-Guo 谢谢
那个，我是业余程序员，我尽量....

**Comment by insub** [comment]
@Eric-Guo 提了～不知道行不行哈

**Comment by Eric-Guo** [comment]
v0.10.0又把这个#215 的改动去掉了，现在理由见#230，所以现在要忽略的话，要用`rescue ResponseError`了。
