### ISSUE TITLE
请问是否有对小程序不限数量二维码（ getwxacodeunlimit ）的支持？

### ISSUE THREAD

**Issue by insub** [Eric-Guo/wechat#217]
就是小程序文档中获取二维码的 B 接口：

https://mp.weixin.qq.com/debug/wxadoc/dev/api/qrcode.html

请问 wechat 有相关的 api 么？

**Comment by Eric-Guo** [comment]
有啊，lib/wechat/api.rb:103

```ruby
    def wxa_get_wxacode(path, width = 430)
      post 'getwxacode', JSON.generate(path: path, width: width), base: WXA_BASE
    end
```

**Comment by insub** [comment]
这个 post 'getwxacode'，我看小程序文档的话，是有限二维码啊，不是无限二维码
另外请问一下，如果我想读取access_token，自己去跟微信服务器发请求的话，请问怎么可以获取呢？直接读取本地临时存放access_token的文件靠谱么？还是 wechat 有什么接口可以读一下？

**Comment by paicha** [comment]
https://github.com/Eric-Guo/wechat/pull/260
