### ISSUE TITLE
请问是否支持网页静默授权？

### ISSUE THREAD

**Issue by fox3013** [Eric-Guo/wechat#221]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842

“以snsapi_base为scope发起的网页授权，是用来获取进入页面的用户的openid的，并且是静默授权并自动跳转到回调页的。用户感知的就是直接进入了回调页（往往是业务页面）”

**Comment by fox3013** [comment]
这个可以手动控制在什么地方传什么scope么？

**Comment by Eric-Guo** [comment]
调用的时候多加一个参数即可`wechat_oauth2('snsapi_userinfo')`

**Comment by fox3013** [comment]
赞👍非常感谢！
