### ISSUE TITLE
请问目前支持小程序的api吗？

### ISSUE THREAD

**Issue by oiahoon** [Eric-Guo/wechat#224]
因为需要用到小程序的**模板消息**，**客服消息**，**登录**，
可能还有**支付**(好像和公众号基本上没区别)
所以如果目前不支持的话，我准备fork出来先自己做

**Comment by Eric-Guo** [comment]
不算完全支持，不一样的地方你可以提PR

**Comment by oiahoon** [comment]
@Eric-Guo 👌，我完成以后会提pr
我想把新增 只属于小程序的api 单独拆个文件来写
和你的最佳实践冲突吗？

**Comment by Eric-Guo** [comment]
可以，你可以从Wechat::ApiBase继承，这样挺好，因为公众号、小程序，企业微信看起来是要各自独立的。

**Comment by oiahoon** [comment]
ヾ(❀^ω^)ノﾞ  我也是这么想的

**Comment by Eric-Guo** [comment]
你还可以这样引用一个gem，这样的话，可以避免本地和远端需要来回切换，比用`path`方便不少。

```
# $ bundle config --local local.hubs /Users/guochunzhong/git/oss/hubs/
gem 'hubs', git: 'https://github.com/bayetech/hubs.git', branch: :master
```

**Comment by oiahoon** [comment]
cool  我正在为这个事情糟心呢，😁
