### ISSUE TITLE
NoMethodError: undefined method `decrypt' for Wechat:Module

### ISSUE THREAD

**Issue by lewislinlin** [Eric-Guo/wechat#231]
when Using Wechat.decrypt(encrypted_data,session_key, iv)
NoMethodError: undefined method `decrypt' for Wechat:Module

**Comment by oiahoon** [comment]
@lewislinlin this feature hasn't been released yet, you can specify the git repo in your `Gemfile`

**Comment by Eric-Guo** [comment]
v0.10.0 just release, sorry let you waiting so long.
