### ISSUE TITLE
最新版本依旧未解决to_json转译问题

### ISSUE THREAD

**Issue by zuoliang0** [Eric-Guo/wechat#234]
https://github.com/Eric-Guo/wechat/blob/0748d252ebb93fe5ae9e52bac3293169696d7774/lib/wechat/concern/common.rb#L153

**Comment by Eric-Guo** [comment]
你是说还是希望合入 #194 ? 我没问题。@fogisland

**Comment by zuoliang0** [comment]
建议合，我现在是本地复写了custom_message_send方法来实现的

**Comment by Eric-Guo** [comment]
好，晚上我看一下，没问题就发个新版本。
