### ISSUE TITLE
关于XML解析存在的安全问题

### ISSUE THREAD

**Issue by hqsiswiliam** [Eric-Guo/wechat#236]
目前使用微信支付中，是否有做关于XML解析安全问题（XXE）的处理。
[关于XML解析存在的安全问题](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5)

**Comment by Eric-Guo** [comment]
> Notably, Nokogiri will treat input as untrusted documents by default, thereby avoiding a class of vulnerabilities known as XXE or “XML eXternal Entity” processing. What this means is that Nokogiri won’t attempt to load external DTDs or access the network for any external resources.

http://www.nokogiri.org/tutorials/parsing_an_html_xml_document.html

应该没有这个问题，不过也不能100%确定，不过现在微信支付是通过[wx_pay](https://github.com/jasl/wx_pay)支持的，无论如何，欢迎PR。@jasl

**Comment by hqsiswiliam** [comment]
我刚刚看了下我在rails项目解析XML的回调的代码，是用Hash.from_xml，结合了[ruby-china中的找到的帖子](https://ruby-china.org/topics/37109)，应该是没有这个问题。希望能帮到后来人。

**Comment by jasl** [comment]
@Eric-Guo @hqsiswiliam 之前有人给 wx_pay 提过，我有回答:

不存在问题，WxPay 解析  XML 使用 ActiveSupport 的 XmlMini，后端默认使用 REXML，由 <https://www.ruby-forum.com/topic/6146175> 可知：

> REXML doesn't support expanding SYSTEM entity. So REXML
doesn't have vulnerability related external content.

如果你自己改用了 LibXML 作为后端，需要看下 <https://www.rubydoc.info/gems/libxml-ruby/2.3.3/LibXML/XML/Parser/Options> 来配置，并按文档说的升级到最新的 LibXml2
