### ISSUE TITLE
支持小程序吗？

### ISSUE THREAD

**Issue by catsky** [Eric-Guo/wechat#243]
我试了服务号，命令行和api模式都可以工作，
但是把app id和secret换成小程序的，就返回
```api unauthorized hint: [xdQYoA0740k199!](48001) (Wechat::ResponseError)```

**Comment by Eric-Guo** [comment]
也有吧，新的账户都有，目前手头没在开发小程序，所以也不能100%确认。

**Comment by sitoto** [comment]
支持的，我用了很久了

**Comment by Eric-Guo** [comment]
现在我也有一个小程序跑了半年了，小程序没有白名单，但是需要配置信任域名。
