### ISSUE TITLE
Forbidden 403

### ISSUE THREAD

**Issue by ziqiaojin** [Eric-Guo/wechat#245]
Hi, thank you for maintaining the wechat gem.
My test wechat public account works fine with the cmd in wechat.
However the signature does not match and I get the text "forbidden" when I access "mydomain/wechat"

here is my wechat.yml

default: &default
#  corpid: "corpid"
#  corpsecret: "corpsecret"
#  agentid:  1
# Or if using public account, only need above two line
  appid: "aaaaaa"
  secret: "aaaaaaaaaaa"
  token: "aaaaaa"
  access_token: "/var/tmp/wechat_access_token"
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  "my_encoding_aes_key"
  jsapi_ticket: "C:/Users/[user_name]/wechat_jsapi_ticket"

I think the credentials are correct because wechat cmd works ok.
do you have any idea how to solve this?
Thank you for you time.

**Comment by Eric-Guo** [comment]
You need either `appid`/`secret` for public/service account or `corpid`/`corpsecret` for Enterprise account.

Seems you provide too many? I guess?
