### ISSUE TITLE
Create a moment in user feed

### ISSUE THREAD

**Issue by alexey** [Eric-Guo/wechat#250]
Hi ! 

I am looking if I can implement API programmable post "moment" to user wall (text and image/s).

I've [seen here on stackoverflow](https://stackoverflow.com/questions/24669946/post-moments-with-wechat-api-on-android) that people do that, but I was not able to find anything about that in documentation or gem.

Is this possible with wechat api ? 
Thanks in advance

**Comment by Eric-Guo** [comment]
There is actually several SDK for wechat, the iOS/Android Client side SDK and the Server side SDK.

Posting "moment" to user wall directly in the server-side SDK. (not only including wechat gem) will never support by Tencent. (according to my understanding of wechat product principle), so it' impossible.

You need to checking iOS/Android Client side SDK instead. (like you provided SO link)
