### ISSUE TITLE
有类似 get_jssign_package 的 api 吗

### ISSUE THREAD

**Issue by jamieYou** [Eric-Guo/wechat#257]
项目新增了新的功能模块，前后端做了分离。前端需要使用微信的 sdk，原本获取签名一直使用这个方法的 [get_jssign_package ](https://github.com/lanrion/weixin_authorize/wiki/js-sdk)。
但是现在的项目已经用了当前这个包，想知道怎么适配 api，我们这边是在 rails 里用 grape 做 api 的。

**Comment by Eric-Guo** [comment]
* [获取token](https://github.com/Eric-Guo/wechat/issues/248#issuecomment-453373054)
* 页面wx.config这个包有现成的方法wechat_config_js，在Rails应该可以直接调用的（即使你用了Grape也一样，除非你只有Grape单独运行），如果想自己写，可以通过Wechat.api.jsapi_ticket.signature(page_url)得到签名，详细代码可以参考wechat_config_js方法的实现。

希望已经回答了你的问题。

**Comment by jamieYou** [comment]
@Eric-Guo 我这边是要 api 返回签名给前端用，wechat_config_js 是用在erb 吧。我先试一下你说的 `Wechat.api.jsapi_ticket.signature`，谢谢🙏。

**Comment by jamieYou** [comment]
可以获取签名了，谢谢
