### ISSUE TITLE
企业微信命令行 AccessTokenExpiredError

### ISSUE THREAD

**Issue by tesths** [Eric-Guo/wechat#258]
使用企业微信命令行时，显示
`Wechat::AccessTokenExpiredError (Wechat::AccessTokenExpiredError)`

已设置 `config/wechat.yml` 里的 `access_token: "/tmp/wechat_access_token"`
试了几个工程，企业微信和公众号都设置了 access_token 的位置，但是都没有在 rails tmp 文件目录找到 `wechat_access_token` 的文件

**Comment by tesths** [comment]
之前设置到 /tmp/wechat_access_token 在 /tmp 目录也没有 wechat_access_token 的记录。
刚刚设置了 config 的 `access_token: "/Users/tesths/Desktop/qywechat/tmp/access_token"` access_token 也没有写入到该文件。
是否有命令行获取 access_token 的方法？或者还是我操作的方法不对。
报错依然是 `Wechat::AccessTokenExpiredError (Wechat::AccessTokenExpiredError)`

**Comment by Eric-Guo** [comment]
是不是你（corpid/corpsecret）或者（appid/secret）输入的不对啊，这样也会导致AccessTokenExpiredError

**Comment by tesths** [comment]
解决了！可能是我哪没设置对吧...现在解决了！非常感谢！
