### ISSUE TITLE
如果在rails中还要进行devise的话是否还要与omniauth-wechat-oauth2 一起使用

### ISSUE THREAD

**Issue by golden05** [Eric-Guo/wechat#26]
如果在rails中还要进行devise的话是否还要与omniauth-wechat-oauth2 一起使用 ，也就是两个插件一起使用啊

**Comment by Eric-Guo** [comment]
现在wechat可以进行企业号开发了，devise合并问题没经验，应该也是可以的。

**Comment by Eric-Guo** [comment]
现在企业号也可以通过新加的`oauth2_url`方法，得到code返回后处理，不一定要用ominiauth也可以用oauth2的，这个issue我先关了。
