### ISSUE TITLE
小程序场景下-客服消息推送-不可用?

### ISSUE THREAD

**Issue by AlberrttChen** [Eric-Guo/wechat#264]
1.已配置wechat.yml的 type:'mp';
2.从而应用内获取Wechat.api为MpApi;
3.WechatsController按照默认的配置;
4.小程序后台配置消息推送为 https://xxx/wechat, 加密, xml格式

现在问题是, 服务器可以正常收到和解析用户给小程序客服发送的消息, 但是响应 request.reply.text “xxx” 好像没有发送成功, 然而也没有异常和报错.不知道是什么情况?

**Comment by Eric-Guo** [comment]
已经搞定了？有坑吗？

**Comment by anke1460** [comment]
小程序消息回复出现楼上一摸一样的情况， 通过wechat custom_text open_id "Text"，是可以收到消息
但通过request.reply.text 'help content'， 收到不到任何反应。不知道@AlberrttChen  是怎么解决的？
