### ISSUE TITLE
在windows 服务器系统上跑您的wechat 文件路径会有问题

### ISSUE THREAD

**Issue by emtfe** [Eric-Guo/wechat#266]
irb(main):002:0> RUBY_PLATFORM
=> "x64-mingw32"
irb(main):003:0> File::SEPARATOR
=> "/"
irb(main):004:0> File::ALT_SEPARATOR
=> "\\"
希望依据上面的RUBY_PLATFORM做判断，而不是简单为wechat.yml 路径，写为 类似 config/wechat.yml
默认*nix  系统 “/”
而忽略了 win 系统的 "\\"

另外非常感谢您的gem

**Comment by Eric-Guo** [comment]
v0.11.5发布了，希望修了吧
