### ISSUE TITLE
还支持4.1 4.2 rails版本么？

### ISSUE THREAD

**Issue by emtfe** [Eric-Guo/wechat#269]
您好，
实际上，用户还有使用4.1 4.2版本的rails
比如

会报错
rails c
Loading development environment (Rails 4.2.7.1)
irb(main):001:0> Wechat.api.callbackip
提示：
NoMethodError: undefined method `callbackip' for true:TrueClass
        from (irb):1

**Comment by Eric-Guo** [comment]
支持的，但你要在一个有wechat配置文件的项目上跑。

**Comment by emtfe** [comment]
我有一个rails 项目, 按您的说明 配置了 wechat.yml  而且是在windows 上跑puma
但用 rails c
提示上面的错误

**Comment by Eric-Guo** [comment]
方便可以给一个github地址，我clone下来看一下吗？

**Comment by emtfe** [comment]
公司内部的site，
但如果您 rails  gemfile 定一个  4.1.6 或者 4.2.7.1
然后gem  install  wechat
应该很容易复现的。 我错过了什么
我现在在跟踪您的gem
貌似到  
@wechat_apis[account.to_sym] ||= ApiLoader.with(account: account) 
with方法
wx_class.new(c.appid, c.secret, token_file, c.timeout, c.skip_verify_ssl, js_token_file)
再到
@access_token = Token::PublicAccessToken.new(@client, appid, secret, token_file)
就不会如我期望的
refresh

**Comment by Eric-Guo** [comment]
那我找一个先试试，之前肯定可以的，最近升级了很多。。。

**Comment by emtfe** [comment]
好的

**Comment by emtfe** [comment]
现在可以了
我实际遇到的是这样一个问题
`require': unable to find a version of 'activesupport' to activate (Gem::LoadError)

我改了 bin/wechat 
由于您倚赖activesupport 我windows 服务器上有多个版本 

#!/usr/bin/env ruby
**require 'rubygems'
gem 'activesupport', '>=4.2.7.1'**

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require 'thor'
require 'wechat'
require 'json'
require 'active_support' # To support Rails 4.2.1, see #17936
require 'active_support/dependencies/autoload'
require 'active_support/core_ext'
require 'active_support/json'
require 'fileutils'
require 'yaml'
require 'wechat/api_loader'
require 'cgi'

。。。。

至少  wechat callbackip 可以跑了
{"ip_list"=>["223.166.222.100", "223.166.222.101", "223.166.222.102", "223.166.222.103",***
access_token 也能正确取值，首次写入正确
{"access_token":"25_wnMl-8RDO7t_vqCoqi0Ag1-9iHV***

再次感谢您
Happy Coding!

**Comment by emtfe** [comment]
仍然 4.2 版本，命令行已经可以正常跑了，
现在 wechats controller 
wechat_responder
这条线， 似乎还是有问题，运行微信客户端提示
**该公众号提供的服务出现故障，请稍后再试**

**Comment by emtfe** [comment]
这个问题 解决了  貌似关闭的issue里有
wechat  改成 wechats 就OK了  wechat_responder 这一条线也通了
resource :**wechats**, only: [:show, :create]
我会逐一尝试接口。 
因为用的是碎片时间，所以不定期写点测试进度。

**Comment by Eric-Guo** [comment]
不容易，windows这边坑是挺多的，你发现issue可以提PR，我能合肯定会合的。

**Comment by Eric-Guo** [comment]
我测试了现在的版本在[Rails 4.2上的使用，好像可以](https://github.com/Eric-Guo/wechat-starter/tree/rails42)，我先关了。

```bash
┌─[±][rails42 ✓][wechat-starter][]
└─▪ bde wechat callbackip
/usr/local/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Using rails project config/wechat.yml development setting...
{"ip_list"=>["223.166.222.100", "223.166.222.101", "223.166.222.102", "223.166.222.103", "223.166.222.104", "223.166.222.105", "223.166.222.106", "223.166.222.107", "223.166.222.111", "223.166.222.112", "223.166.222.117", "223.166.222.118", "101.91.60.80", "101.91.60.81", "121.51.66.16", "121.51.66.19", "121.51.66.26", "121.51.66.120", "157.255.192.54", "157.255.192.55", "58.60.9.75", "58.60.9.76", "58.60.9.77", "58.60.9.78", "59.36.121.222", "59.36.121.223", "121.51.162.73", "121.51.162.74", "121.51.162.55", "103.7.30.71", "103.7.30.70", "103.7.30.69", "103.7.30.68", "203.205.219.187", "203.205.219.188", "203.205.219.189", "203.205.219.190"]}
```
