### ISSUE TITLE
NoMethodError: private method `next_migration_number'

### ISSUE THREAD

**Issue by zpdsky** [Eric-Guo/wechat#270]
有人反映了个出错信息

```
private method `next_migration_number' called for Wechat::Generators::SessionGenerator:Class (NoMethodError)
```

 -- <https://ruby-china.org/topics/39006>

我看了下大概是这个 [commit](https://github.com/Eric-Guo/wechat/commit/2a329cf4c269c7f17f2e20f4b81cdb94ea0cb69d#diff-ccb202bf88c8e17493a564aff1cc1e18L25) 里 `private` 部分的改动导致的。`next_migration_number` 应该期待是 public method.

**Comment by Eric-Guo** [comment]
Fix at release `0.11.6`
