### ISSUE TITLE
如何在 on  :text 代码块里面得到 wechat_configs 对应的 id？

### ISSUE THREAD

**Issue by sitoto** [Eric-Guo/wechat#274]
如下：
```
  on :text, with: 'help' do |request|
   # 这里如何得到对应的 wechat_config  的id 呢？
    request.reply.text 'help content'
  end
```

**Comment by Eric-Guo** [comment]
> Use Wechat.api or Wechat.api(:default) to represent the default wechat api. Use Wechat.api(:wx2) to call for wechat api of account wx2.

文档有写。

**Comment by sitoto** [comment]
> > Use Wechat.api or Wechat.api(:default) to represent the default wechat api. Use Wechat.api(:wx2) to call for wechat api of account wx2.
> 
> 文档有写。

如何在  on :text,...

end
里面得到 这个“wx2” 呢？

**Comment by sitoto** [comment]
一个站点下面有多个公众号，
用户发送内容和返回的内容存到数据库，同时记录是来自哪个公众号。不知道怎么写啊 @Eric-Guo

**Comment by Eric-Guo** [comment]
目前需要多个wechat_responder，并且需要多个Controller hosting 多个公众号。（其实文档也有写）

```ruby
  wechat_responder account: :wx2
```

在responder下，被动回复消息用`request.reply.text "🤔"`，主动消息还是通过`wechat.api(:wx2)`。

如果希望在一个Controller下处理多个公众号，需要account_from_request，文档其实也写了。
