### ISSUE TITLE
临时素材无法获取

### ISSUE THREAD

**Issue by 0000sir** [Eric-Guo/wechat#278]
微信API变更后，已经无法通过获取永久素材的方式获得用户发来的图片，需要调用获取临时素材接口 https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Get_temporary_materials.html

**Comment by Eric-Guo** [comment]
似乎无需wechat端处理，程序员在调用时注意即可。

**Comment by 0000sir** [comment]
直接调用 Wechat.api.get_material 调用的是获取永久素材接口，如果是用户发来的图片，会提示 invalid media id，这个get_material还有高级用法？

我目前的方案还是直接访问接口的url

```ruby
    require "down"
    require "fileutils"
    access_token = Wechat.api.access_token
    url = "https://api.weixin.qq.com/cgi-bin/media/get?access_token=#{access_token.token}&media_id=#{media_id}"
    begin
      temp = Down.download(url)
      images.attach io: temp, filename: temp.original_filename
    rescue => e
      p e.message
    end
```

**Comment by Eric-Guo** [comment]
有临时素材接口的[API](https://github.com/Eric-Guo/wechat/blob/master/lib/wechat/api_base.rb#L23)啊。。。可以直接调用，README里面也写了`wechat media [MEDIA_ID, PATH]`，可以用吗？
