### ISSUE TITLE
配置文件的token指的是什么？

### ISSUE THREAD

**Issue by kxu1988** [Eric-Guo/wechat#279]
default: &default
  appid: "app_id"
  secret: "app_secret"
  token:  "app_token"  **// 这个token指的是什么？**
  access_token: "/var/tmp/wechat_access_token"
  jsapi_ticket: "/var/tmp/wechat_jsapi_ticket"

**Comment by Eric-Guo** [comment]
token 指的是 消息推送启用并设置消息推送配置后，用户发给小程序的消息以及开发者需要的事件推送，在微信后台，开发，开发设置，消息推送中设置。
