### ISSUE TITLE
微信公众平台问题

### ISSUE THREAD

**Issue by RanX12** [Eric-Guo/wechat#282]
您好，请问您的这个 gem 是只支持发送/接收消息的功能吗？我想做一个微信扫码关注公众号然后登录的功能，现在找不到合适的 gem...

**Comment by Eric-Guo** [comment]
都支持的，用`wechat` gem，类似于这样就能拿到用户的信息。

```ruby
  def applies
    wechat_oauth2 do |userid|
      @user_hash = Wechat.api.user(userid)
      if dc_account = sccsa_account(@user_hash).presence
        if User.find_by(name: dc_account)
          show_applies(dc_account)
        else
          render 'weui/message_box', locals: { title: '配送账号不存在', description: '请联系协会工作人员检查配置账号' }
        end
      else
        render 'weui/message_box', locals: { title: '无配送账号', description: '无法进行此项查询，请联系协会工作人员添加' }
      end
    end
  end
```

**Comment by RanX12** [comment]
哦哦，我是个初级 railser，还没开发过微信相关的，我想问问就是我只需要安装 ```wecaht``` gem，然后通过’微信公众平台命令行‘获取到二维码，通过回调地址获取到用户是否关注公众号（服务号）就可以了是吗？谢谢～

**Comment by Eric-Guo** [comment]
没那么简单，默认的二维码是进入公众号的，你需要在公众号菜单里面配上Rails 应用的页面，然后在页面上再用上面的代码。

**Comment by RanX12** [comment]
好的，订阅号 和 服务号都是可以做吧？

**Comment by Eric-Guo** [comment]
一样的。（不过有些功能订阅号没有，只有认证的订阅号才有）

**Comment by RanX12** [comment]
我看了一下文档，
![image](https://user-images.githubusercontent.com/46048444/95643907-09045700-0ae5-11eb-91e1-aca5aae82cc0.png)
认证了的订阅号也没有 “生成带参数二维码”功能，那下面这三个方法也就没用了：
![image](https://user-images.githubusercontent.com/46048444/95643956-829c4500-0ae5-11eb-9a92-defccb0c0fa9.png)

也就是说明订阅号不能做“网页扫码关注公众号”然后登录/注册的功能了？

**Comment by Eric-Guo** [comment]
试了才知道，另外API只是区分了企业号和公众号，对于服务号和订阅号没有做区分，[README也写了](https://github.com/Eric-Guo/wechat/blob/main/README-CN.md#关于接口权限)。

**Comment by RanX12** [comment]
您好，我之前看了之后没时间去做，然后现在开始做这个，想问问这里在服务器配置好路由之后，我在微信测试号上配置了```http://*****.com/wechat```，我先是默认返回的 true，没有去做验证，服务器显示 200 成功了，但是微信这边显示配置失败了，
![image](https://user-images.githubusercontent.com/46048444/97408390-f6887b00-1936-11eb-80d9-c77c95739f06.png)
![image](https://user-images.githubusercontent.com/46048444/97408435-099b4b00-1937-11eb-8153-d0d5ece645f5.png)
我配置的路由是访问的 show，然后如果我要用```wechat_responder```的话，我控制器应该用 ```on :? ```什么来接收这个信息呢？

**Comment by Eric-Guo** [comment]
必须启用wechat_responder，无需写任何代码即可处理接口配置信息。

**Comment by RanX12** [comment]
好的，谢谢，另外我想问一下在```README-CN.md```没有找到的信息，access_token 是会变的嘛，然后是需要我自己定时通过 url 去获取 access_token，然后存到 redis 的吗？

**Comment by Eric-Guo** [comment]
用WeChat gem不用自己维护token（任何token），一开始不需要用redis，redis是给多个服务器跑同一个rails app准备的，如果你一开始就预计到写的Rails应用有一秒200 request以上的负载，请直接用go-lang的gin 框架，或者Elixir的phoenix。
