### ISSUE TITLE
获取Ticket错误，Wechat::ResponseError - api unauthorized

### ISSUE THREAD

**Issue by RanX12** [Eric-Guo/wechat#283]
我在程序里和微信调试工具获取 ticket 的时候，都报了这个错，我用微信官方的测试号是可以：获取 ticket => 获取二维码 => 扫码关注并且登录，我把配置改为已认证的订阅号就会报错，
![image](https://user-images.githubusercontent.com/46048444/97773827-12d22500-1b8e-11eb-9be1-89011f2f6bfc.png)
![image](https://user-images.githubusercontent.com/46048444/97773846-2ed5c680-1b8e-11eb-844c-5b288381a7ee.png)

这是获取代码
![image](https://user-images.githubusercontent.com/46048444/97773857-49a83b00-1b8e-11eb-9514-e26dd6fcc870.png)

**Comment by Eric-Guo** [comment]
这种低级错误不可能是wechat gem的bug，请检查你的配置是否正确。

**Comment by RanX12** [comment]
配置是可以的，微信的订阅号是不支持获取带参数的二维码，也就是 qrcode_create_scene 这个命令或许是不能用的，```wechat gem```确实是没有做服务号和订阅号的区分，但是用订阅号去调用 qrcode_create_scene 会报错，服务号不会，这个错也应该是微信那边返回的，不是 ```wechat gem```的bug。
