### ISSUE TITLE
关于 JS-SDK 的疑问

### ISSUE THREAD

**Issue by RanX12** [Eric-Guo/wechat#285]
你好，我在 README-CN.md 中看到有 ```wechat_config_js```此方法，我在使用的时候还需要在
```
wechat_config_js debug: false, api: %w(updateTimelineShareData)
```
 这里面添加我的 api 以及 签名：timestamp、nonceStr、signature这些吗？
我现在是这样写的，点了之后没有任何反应 ，日志没有报错，前端控制台也没有报错，所以我有点疑问。

![image](https://user-images.githubusercontent.com/46048444/101980760-c1e04100-3ca2-11eb-84a0-be04d642af91.png)

![image](https://user-images.githubusercontent.com/46048444/101980731-89d8fe00-3ca2-11eb-9348-338c4953af6f.png)

我是先配置 JS接口安全域名，然后在控制器中添加 wechat_api，然后在 view 中使用 ```wechat_config_js``` ，不知道是不是哪步出了问题，请指点指点...

-------

下午研究了一下，
```javascript
javascript:
  wx.ready(function () {
    console.log('---------')
    console.log('已验证')
    wx.updateTimelineShareData({
      title: '测试标题',
      link: '#{Figaro.env.TRUSTED_DOMAIN_FULLNAME!}',
      imgUrl: 'http://demo.open.weixin.qq.com/jssdk/images/p2166127561.jpg',
      success: function () {
        console.log('设置成功')
      }
    })
  })
```
像这样无法调用到 ```ready```里面到函数，看起来像是没有验证成功。
因为我直接写的话，是有弹框提醒的
```
= link_to 'javascript: wx.updateTimelineShareData({title: 'xxxx', link: '***', imgUrl: '**'}), alert('已注册获取“发送给朋友”状态事件');'
```

**Comment by Eric-Guo** [comment]
> 我在使用的时候还需要添加我的 api 以及 签名：timestamp、nonceStr、signature这些吗？

不用，呼叫`wechat_config_js`已经帮你生成了。

> 像这样无法调用到 ready里面到函数

是的，因为微信的脚本需要包裹的是：`application/javascript`，而不是普通网页的`javascript`
