### ISSUE TITLE
消息发送疑问

### ISSUE THREAD

**Issue by RanX12** [Eric-Guo/wechat#291]
@Eric-Guo  您好，请问在用户点击某个菜单之后，发送如图这种消息，是用的哪个 API 呢？如果用```发送**客服消息```等API，发送的不是这种推送文章
![image](https://user-images.githubusercontent.com/46048444/106706518-c550d280-662a-11eb-81f7-f954c424e264.png)

```ruby
articles = YAML.load(File.read(Rails.root.join('config/articles.yaml')))

request.reply.news(articles['articles'])
```
我用测试号测试时，发送的是这样的的消息：
![image](https://user-images.githubusercontent.com/46048444/106715528-2337e700-6638-11eb-91cf-6314042b9071.png)

我不确定订阅号发送的时候什么样子，麻烦解答一下谢谢了

**Comment by Eric-Guo** [comment]
用的是[Wechat.api.news_message_send](https://github.com/thape-cn/web/commit/ea87bd1f88818c40f0e498e8a88ab867407c2932) API

**Comment by RanX12** [comment]
> 用的是[Wechat.api.news_message_send](https://github.com/thape-cn/web/commit/ea87bd1f88818c40f0e498e8a88ab867407c2932) API

我用 ```rails c```进入控制台，运行```Wechat.api(:default).methods```，没有这个方法，在 WechatController 中加了wechat_api 和 wechat_responder，使用 wechat.news_message_send 也没有这个方法

**Comment by Eric-Guo** [comment]
request.reply.news用于立刻返回消息（微信推送给你），其他两个是类似的，news_message_send目前我只用在企业号，如果你不是，可以试试看能否调用，如果可以，应该可以放出来。

**Comment by RanX12** [comment]
好的，那我应该是直接使用 request.reply.news
