### ISSUE TITLE
Ruby 3.0 + Rails 6.1 shows DEPRECATION WARNING running rspec

### ISSUE THREAD

**Issue by xinyifly** [Eric-Guo/wechat#294]
### Output

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

    Rails.application.reloader.to_prepare do
      # Autoload classes and modules needed at boot time here.
    end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.

Check the "Autoloading and Reloading Constants" guide to learn more about how
Rails autoloads and reloads.
 (called from <top (required)> at /path/to/my/rails/project/config/environment.rb:5)
```

### Versions

```
# ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
```

```
# rails --version
Rails 6.1.3
```

```
# rspec --version
RSpec 3.10
  - rspec-core 3.10.1
  - rspec-expectations 3.10.1
  - rspec-mocks 3.10.2
  - rspec-rails 4.0.2
  - rspec-support 3.10.2
```

### Notes

- The WARNING gets cleared if I change to `gem 'wechat', require: false` in Gemfile
- With `rails generate wechat:redis_store`
- Related to https://github.com/rails/rails/issues/36546

**Comment by Eric-Guo** [comment]
Can you try `gem "wechat", git: "https://github.com/Eric-Guo/wechat", branch: :zeitwerk`, I plan to only support Rails 6 and using zeitwerk mode in next release, but still under test.

**Comment by xinyifly** [comment]
@Eric-Guo 
With `gem 'wechat', git: 'https://github.com/Eric-Guo/wechat', branch: :zeitwerk` , the DEPRECATION WARNING still exists.

**Comment by goofansu** [comment]
See the same issue after upgrading Rails 6.1, but I'm not sure whether it is caused by this gem.

**Comment by Eric-Guo** [comment]
I can not reproduce in Rails 6.1 without Rspec project, but I do see some change suggesting like https://github.com/Sorcery/sorcery/pull/255

**Comment by Eric-Guo** [comment]
@goofansu  @xinyifly Not sure if it's works, but seems should be a valid fix, so kindly test?

**Comment by xinyifly** [comment]
@Eric-Guo LOL, with latest `zeitwerk` branch, the DEPRECATION WARNING disappeared, nice work, Thank you!.

**Comment by Eric-Guo** [comment]
Release 0.13.0 now in zeitwerk mode and support Rails 6.0+ only.
