### ISSUE TITLE
Psych::BadAlias (Unknown alias: default)

### ISSUE THREAD

**Issue by otorain** [Eric-Guo/wechat#308]
## 问题描述
在处理微信的回调时报这个错，ruby-3.0.1 没有这个问题。google 后好像跟 YAML 的别名有关，将 gem 下载下来，把所有`YAML.load`方法调用到的地方添加了`aliases: true`这个 option 后就可以了。修改后的代码提交了 [PR](https://github.com/Eric-Guo/wechat/pull/309)

## 环境
ruby: 3.1.0
rails: 7.0.2

## 报错详细信息
```bash
Psych::BadAlias (Unknown alias: default):

app/controllers/wechats_controller.rb:4:in `<class:WechatsController>'
app/controllers/wechats_controller.rb:3:in `<main>'
app/middlewares/case_converter_middleware.rb:38:in `call'
```

**Comment by otorain** [comment]
![image](https://user-images.githubusercontent.com/25400144/153714956-61c56bc6-e0b8-4d4f-b311-a73aedd8d5d4.png)

看 ruby 3.1.0 的升级内容发现是由于 psych 这个 gem 升级后导致的，将这个 gem 降级为 '3.3.2' 版本也能就觉这个问题。具体在 Gemfile 里边添加：
```ruby
gem 'psych', "3.3.2"
```

**Comment by Eric-Guo** [comment]
Release v15.1 to fix
