### ISSUE TITLE
是不是要向psych (5.0.0)做一些兼容处理了？

### ISSUE THREAD

**Issue by oxygen-xx** [Eric-Guo/wechat#314]
是不是要向psych (5.0.0)做一些兼容处理了？
现在psych已经升级为5.0，再安装 wechat时，有问题。

**Comment by Eric-Guo** [comment]
目测 `psych 5` 应该是为 ruby 3.2 准备的，直接装 `gem install psych --default` 甚至会搞崩 gem （别尝试，昨天我试过了）

**Comment by Eric-Guo** [comment]
5.0.1似乎没啥问题了，发布了`0.16.2`
