### ISSUE TITLE
Responder#on方法中关于message type的限制似乎是没必要的

### ISSUE THREAD

**Issue by leepood** [Eric-Guo/wechat#318]
这一段代码不应该对消息类型有限制

https://github.com/Eric-Guo/wechat/blob/48841c0e40cf103a606f8bb8b7fdbc0400298f52/lib/wechat/responder.rb#L22

否则这边的两段代码都无法被触发
https://github.com/Eric-Guo/wechat/blob/48841c0e40cf103a606f8bb8b7fdbc0400298f52/lib/wechat/responder.rb#L53
https://github.com/Eric-Guo/wechat/blob/48841c0e40cf103a606f8bb8b7fdbc0400298f52/lib/wechat/responder.rb#L55

对于未知的`message type` 这里会统一处理
https://github.com/Eric-Guo/wechat/blob/48841c0e40cf103a606f8bb8b7fdbc0400298f52/lib/wechat/responder.rb#L58

**Comment by Eric-Guo** [comment]
是的，v0.17.2已经去掉这个限制，感谢
