### ISSUE TITLE
为何要添加限制Rails 的版本？

### ISSUE THREAD

**Issue by xiajian** [Eric-Guo/wechat#32]
从文件的方面来看，这就是一个类似库的项目，为何会依赖特定的版本的Rails？ 刚好比我的生产环境高0.01。

**Comment by Eric-Guo** [comment]
你指rails [3.2.14](https://github.com/skinnyworm/wechat-rails/blob/master/wechat-rails.gemspec#L17)？那就升级一下吧，好多漏洞啊。。

**Comment by Eric-Guo** [comment]
@xiajian 现在只要求[3.2](https://github.com/Eric-Guo/wechat/blob/master/wechat.gemspec#L18)了，所以你可以用了，不过真的没在3.2上怎么测试，还有这个项目的确不应该依赖Rails，不过这个就要我慢慢改了。

**Comment by feitian124** [comment]
@Eric-Guo 勤奋的人儿, 让我助你一臂之力 :smile:

**Comment by Eric-Guo** [comment]
@feitian124 :+1: 我还要熟悉代码，很多东西一般Rails应用用不到，Gems里面才有，所以这个的优先级不是那么高。。。

**Comment by Eric-Guo** [comment]
Version 4.2已经不限制版本了。
