### ISSUE TITLE
我想将这个项目的所有权转交给其他感兴趣的开发者，请大家报名

### ISSUE THREAD

**Issue by skinnyworm** [Eric-Guo/wechat#33]
由于我现在的主要开发语言不再是Ruby，所以可能没有太多精力维护这个项目了。希望Ruby社区的开发者能接手这个项目。

这个项目有很多有趣的想法，特别是API设计上，至今我还觉得挺满意的，但是很多细节包括

* 是否要使用restful-client
* 对新API的支持
* 如何配置本地的AccessToken存储服务等

还需要进一步的改进，有兴趣的开发者可以回复报名，谢谢。

**Comment by bobzhen** [comment]
如果微信api开发的中文文档没有差劲，个人可以考虑经常commit。
well，@skinnyworn，你已经做了很多事情了，希望其他有兴趣的developer可以继续薪火相传。
谢谢！

**Comment by skinnyworm** [comment]
@bobzhen 是的，微信的API设计挺业余的

**Comment by feitian124** [comment]
现在玩啥语言去了? 
我对 nodejs 兴趣挺浓, 上个项目上 ember 踩了不少坑啊, 外加像 rails 这么成熟的框架还是没有啊, 正经做项目,还是保守点选择 rails 了.

**Comment by skinnyworm** [comment]
语言本身不重要，关键还是看应用场景，

Ruby的语法很精练，很适合做DSL和WEB应用, 但却缺失一些我需要的关键特性。

JS语法很啰嗦，但其异步IO的完整生态很适合并行处理的任务。

当然还有scala, clojure,go各有各的特点和优势，应用场景决定了工具的选择，而语言只是工具的一部分。

**Comment by feitian124** [comment]
您好, 我的项目有点重度依赖你这个 repo 哎, 没更新挺可惜的. 方便把所有权转给我吗, 我来维护吧.

我已经添加了一些有用的 commit: 
1. 添加了 jsapi_ticket 支持
2. 修复了 access_token 读取的bug

https://github.com/feitian124/wechat-rails/commits/ming

**Comment by Eric-Guo** [comment]
支持@feitian124，虽然我已经合并了他的[ming branch](https://github.com/feitian124/wechat-rails/commits/ming)，还有其他一些enhancement到#39，其实在同性交友网站github上也算挺活跃的，所以，其实，也可以考虑我一下。。

**Comment by Eric-Guo** [comment]
@feitian124 @skinnyworm 我拿到[wechat](http://rubygems.org/gems/wechat)这个名字的gem发布权了，所以现在官网应该是[Eric-Guo/wechat](https://github.com/Eric-Guo/wechat)了，我会好好维护这个gem，打败[weixin_rails_middleware](https://github.com/lanrion/weixin_rails_middleware)的 :smile:

**Comment by skinnyworm** [comment]
@Eric-Guo @feitian124 ,我可以将你们二位加入committer中吗？

**Comment by skinnyworm** [comment]
@Eric-Guo @feitian124 已将二位加入Collaborators，你们可以直接push code了，我更倾向于将这个repo  直接transfer给@Eric-Guo, 貌似他会拥有更好的Gem名 :)

**Comment by feitian124** [comment]
@skinnyworm 谢谢, 支持 @Eric-Guo

**Comment by skinnyworm** [comment]
@Eric-Guo 已发送transfer 请求，请接受 :P

**Comment by Eric-Guo** [comment]
@skinnyworm 好的，我一定会薪火相传的。
