### ISSUE TITLE
关于access token的过期时间

### ISSUE THREAD

**Issue by XunChangqing** [Eric-Guo/wechat#41]
感谢贡献，并恭喜接手项目呵呵。
我看代码里面判断过期时间是3*60,3个小时？微信文档里面是2个小时吧？另外以后是否可以提供被动刷新token的方法呢。

**Comment by XunChangqing** [comment]
另外还有个问题，api的初始化可以增加appid，secret，token file和ticketfile的参数不，这样一个服务器就可以处理很多公众号，这个很有用呢，并且现在的responder就考虑了这个问题，是否不太一致呢。

**Comment by Eric-Guo** [comment]
[3*60](https://github.com/Eric-Guo/wechat/blob/master/lib/wechat/access_token.rb#L17)指的是三分钟，也就是说会提前3分钟刷新。

针对[多个公众号在responder里面已经支持](https://github.com/Eric-Guo/wechat/#rails-为每个responder配置不同的appid和secret)了，主动调用命令行模式还没有，我也在考虑添加。

**Comment by XunChangqing** [comment]
感谢，前面那个没仔细看呵呵，
另外其他获取二维码什么的，有计划不

**Comment by Eric-Guo** [comment]
有的，等我用到了。。欢迎PR。😊

**Comment by Eric-Guo** [comment]
多配置文件命令行模式已添加。

**Comment by leepinc** [comment]
我的token10分钟就过期了，这是什么原因？

**Comment by Eric-Guo** [comment]
目前token这块应该没有bug了，所以请检查是否其他原因，另外token过期会自动刷新，所以无所谓的。
