### ISSUE TITLE
希望添加多客服消息转发功能

### ISSUE THREAD

**Issue by cestivan** [Eric-Guo/wechat#42]
下面是官方原文，[出处](http://dkf.qq.com/)

`如果公众号处于开发模式，需要在接收到用户发送的消息时，返回一个MsgType为transfer_customer_service的消息，微信服务器在收到这条消息时，会把这次发送的消息转到多客服系统。用户被客服接入以后，客服关闭会话以前，处于会话过程中，用户发送的消息均会被直接转发至客服系统。`

**Comment by Eric-Guo** [comment]
[加了](https://github.com/Eric-Guo/wechat#多客服消息转发)，0.3.0版本支持。
