### ISSUE TITLE
报告一个问题

### ISSUE THREAD

**Issue by XunChangqing** [Eric-Guo/wechat#43]
我尝试反复获取access_token，发现每次获取的access token都不同，但是我看代码应该不会这样的。
我发现如果启动服务器之前，如果/var/tmp/access_token文件不存在，则这个问题总是存在。
我调试了一下发现读出文件的created_at为0，所以总是刷新
如果在启动server之前文件就存在，则貌似没有问题。

另外这里不会发生多线程写文件的冲突吗？

**Comment by Eric-Guo** [comment]
反复获取access_token，得到不同的值是正常的，只要调用接口就会得到不一样的token。

多线程写文件，现在是原子的了。
