### ISSUE TITLE
wechats controller 关注后回复图文消息失效

### ISSUE THREAD

**Issue by qiao2818** [Eric-Guo/wechat#49]
Ruby 2.2.3
Rails 4.2.3

request.reply.news(0...1) do |article, i|
article.item title: "title", description: "desc", pic_url: 'http://www.baidu.com/img/bdlogo.gif', url: 'http://www.baidu.com/'
end

这里之前是没有问题的，但是现在是失效的，原因未知，请帮忙检查，谢谢

**Comment by feitian124** [comment]
失效报什么错呢? 错误码或者异常是什么?

**Comment by Eric-Guo** [comment]
无法复现问题，已经补了一个测试，也在线上实际做了测试，`1条新闻`是可以收到的（企业号），当然，现在更推荐的写法是Readme里面那种，也就是`request.reply.news(news_from_db)`，里面直接放从数据库查到的Active Record对象，虽然你写range一样认（因为都可以相应each_with_index和take方法）

```
  # 当请求的文字信息内容为'<n>条新闻'时, 使用这个responder处理, 并将n作为第二个参数
  on :text, with: /^(\d+)条新闻$/ do |request, count|
    # 微信最多显示10条新闻，大于10条将只取前10条
    news = (1..count.to_i).each_with_object([]) { |n, memo| memo << { title: '新闻标题', content: "第#{n}条新闻的内容#{n.hash}" } }
    request.reply.news(news) do |article, n, index| # 回复"articles"
      article.item title: "#{index} #{n[:title]}", description: n[:content], pic_url: 'http://www.baidu.com/img/bdlogo.gif', url: 'http://www.baidu.com/'
    end
  end
```
