### ISSUE TITLE
普通controller如何调用jsapi_ticket?

### ISSUE THREAD

**Issue by goofansu** [Eric-Guo/wechat#51]
除了在controller里引入`wechat_responder`，还有别的方法可以在这个controller中调用`PlainController.wechat.jsapi_ticket.signature(request.original_url)`吗？

**Comment by Eric-Guo** [comment]
`Wechat.api.jsapi_ticket.jsapi_ticket.signature(request.original_url)`试试这个？

**Comment by goofansu** [comment]
@Eric-Guo 这个可以，谢谢

**Comment by goofansu** [comment]
这个问题先关闭了。如果需要进行改进，再另外开一个PR吧
