### ISSUE TITLE
调用jsapi_ticket出现reach max api daily quota limit hint: [VAB1bA0573vr20](45009)

### ISSUE THREAD

**Issue by goofansu** [Eric-Guo/wechat#52]
每次进入搜索页面就调用一次api填充页面的jssdk签名，因为在搜索页面中我要使用jssdk获取用户的地理位置。

示例controller如下：

``` ruby
class SearchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_jssdk

  def new
    @query = Query.new
  end

  def set_jssdk
      @hash = Wechat.api.jsapi_ticket.signature(request.original_url)
  end
end
```

问题：出现`reach max api daily quota limit hint`错误，但在重启rails服务后正常。

说明：
* appid和secret没有给别人使用
* 只开了一个rails服务

**Comment by goofansu** [comment]
这次是真的超出限制了，但是原因不知道。

之前有两次确实是重启就没这个错误了。

**Comment by Eric-Guo** [comment]
确保你缓存了jsapi_ticket？应该不是在`tmp/jsapi_ticket`就是在`/var/tmp/wechat_jsapi_ticket`，当然，你也可以wechat.yml里面的`jsapi_ticket`项配置。

**Comment by goofansu** [comment]
@Eric-Guo 是在`tmp/jsapi_ticket`里的，我换个号再观察下

**Comment by feitian124** [comment]
你看看时间戳 created_at 是不是最新的? 把这个文件删除了再试下~
没有针对"超过配额"的异常做过特殊处理, 正常情况下不会超过配额.

**Comment by goofansu** [comment]
@feitian124 恩，我再看下，之前我把文件删除了，没看文件内容

**Comment by goofansu** [comment]
合并https://github.com/Eric-Guo/wechat/pull/54后，这个问题就解决了

**Comment by Eric-Guo** [comment]
0.6.0版本已经包括了#54的修正。

**Comment by goofansu** [comment]
终于可以升级了，感谢
