### ISSUE TITLE
添加错误码40001处理

### ISSUE THREAD

**Issue by jasper-fu** [Eric-Guo/wechat#57]
当使用多台机器时，除了42001: access_token超时, 40014:不合法的access_token，还有可能出现{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest hint"} 错误。感觉也需要更新access_token.

**Comment by Eric-Guo** [comment]
现在有了，通过`gem 'wechat', github: 'Eric-Guo/wechat'` 帮忙测一下？

**Comment by Daimhim** [comment]
怎么处理啊，现在调微信登陆出现这个错误errcode":40001

**Comment by Eric-Guo** [comment]
这个是你没有提供对的appid/secret，或者设置了IP白名单，不是wechat gem的问题。
