### ISSUE TITLE
menu.yaml要放在哪里，skip_verify_ssl: true又写入哪个配置文件

### ISSUE THREAD

**Issue by gentcys** [Eric-Guo/wechat#59]
新手，请见谅。

**Comment by Eric-Guo** [comment]
menu.yaml放在任何地方都可以，建议放在config文件夹下，skip_verify_ssl放的位置已经在[README中有介绍](https://github.com/Eric-Guo/wechat#rails-全局配置)。

**Comment by gentcys** [comment]
寫入menu.yaml後執行`wechat menu_create menu.yaml` 返回 `No such file or directory`，根據提示的文件地址找到gem下wechat文件 318行`menu = YAML.load(File.read(menu_yaml_path))`，但文件中找不到申明`menu_yaml_path`的地方。需要對`menu.yaml`進行系統權限更改嗎？
