### ISSUE TITLE
本地接入调试成功，部署到Heroku就403。

### ISSUE THREAD

**Issue by gentcys** [Eric-Guo/wechat#60]
参数写死：`signature=9beb5b249c3677956590959b584896d40dba8785&timestamp=12345&nonce=abcde&echostr=hahaha4`
本地调试顺利返回`echostr`值，部署到Heroku就403了，头大中，验证方法提取出来写入controller还能通过：

    class WechatSupportsController < ApplicationController
      skip_before_filter :verify_authenticity_token
      before_filter :check_weixin_legality
    
      def show
        render :text => params[:echostr]
      end
    
      def create
        if params[:xml][:MsgType] == "text"
          render "echo", :formats => :xml
        end
      end
      private
        def check_weixin_legality
          array = ["wechat", params[:timestamp], params[:nonce]].sort
          render :text => "Forbiden", :status => 403 if params[:signature] != Digest::SHA1.hexdigest(array.join)
        end
    end

wechat.yml:

    default: &default
      appid: "*******"
      secret: "**********"
      token:    "wechat"
      access_token: "/var/tmp/wechat_access_token"
    
    production:
      appid: <%= ENV['WECHAT_APPID'] %>
      secret: <%= ENV['WECHAT_APP_SECRET'] %>
      token:      <%= ENV['WECHAT_TOKEN'] %>
      access_token:  <%= ENV['WECHAT_ACCESS_TOKEN'] %>
    
    development:
      <<: *default
    
    test:
      <<: *default

**Comment by Eric-Guo** [comment]
Heroku不允许写入文件。。

**Comment by Eric-Guo** [comment]
你后来怎么解的？我还在计划将token写入部分改写成支持Heroku呢。。

**Comment by gentcys** [comment]
为了测试应用，我用ngrok直接在本地测试了。
正面这个问题的话，Heroku支持Environment variable设置，可以用`heroku config:set ENV_NAME=env_value`写入自动刷新文件？（因为好像access_token是两小时过期？）

**Comment by Eric-Guo** [comment]
@gentcys 现在0.7.4支持redis存贮token了，可以试试。

**Comment by gentcys** [comment]
@Eric-Guo 好棒，过年试试看。
