### ISSUE TITLE
"application did not send a complete response

### ISSUE THREAD

**Issue by gentcys** [Eric-Guo/wechat#61]
App 30814 stderr: [ 2015-10-21 11:32:42.9762 30835/0xb8107b48(Worker 1) utils.rb:86 ]: ***         Exception RuntimeError in Rack application object (Missing `secret_token` and                         `secret_key_base` for 'production' environment, set these values in                         `config/secrets.yml`) (process 30835, thread 0xb8107b48(Worker 1)):
    App 30814 stderr:       from /home/cong/projects/pingtanfeiyu/vendor/bundle/ruby/2.2.0                    /gems/railties-4.2.4/lib/rails/application.rb:534:in `validate_secret_key_config!'
    App 30814 stderr:       from /home/cong/projects/pingtanfeiyu/vendor/bundle/ruby/2.2.0                    /gems/railties-4.2.4/lib/rails/application.rb:246:in `env_config'
    App 30814 stderr:       from /home/cong/projects/pingtanfeiyu/vendor/bundle/ruby/2.2.0                    /gems/railties-4.2.4/lib/rails/engine.rb:514:in `call'
    App 30814 stderr:       from /home/cong/projects/pingtanfeiyu/vendor/bundle/ruby/2.2.0                    /gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
    App 30814 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger                                        /rack/thread_handler_extension.rb:94:in                         `process_request'
    App 30814 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler                /thread_handler.rb:151:in `accept_and_process_next_request'
    App 30814 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler                /thread_handler.rb:112:in `main_loop'
    App 30814 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger                                        /request_handler.rb:415:in `block (3 levels) in                 start_threads'
    App 30814 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:112:in `block in     create_thread_and_abort_on_exception'
    [ 2015-10-21 11:32:42.9769 30188/b61d1b40 age/Cor/Req/Utils.cpp:95 ]: [Client 1-11] Sending     502 response: application did not send a complete respons                                                    

  
部署环境：`passenger + nginx + digitalocean + ubuntu`
微信认证：token验证失败
模拟请求：`http://domain/wechat?signature=signature_value&echostr=echostr_value&timestamp=timestamp_value&nonce=nonce_value`返回`Incomplete response received from application`

**Comment by Eric-Guo** [comment]
Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`

报的错很清晰啊，不是wechat gems的问题。
