### ISSUE TITLE
自定義菜單, no such file or directory

### ISSUE THREAD

**Issue by gentcys** [Eric-Guo/wechat#62]
寫入menu.yaml後執行`wechat menu_create menu.yaml` 返回 `No such file or directory`，根據提示的文件地址找到gem下wechat文件 318行`menu = YAML.load(File.read(menu_yaml_path))`，但文件中找不到申明`menu_yaml_path`的地方。是我哪裏錯了，還是需要對`menu.yaml`進行系統權限更改嗎？

**Comment by Eric-Guo** [comment]
一般不需要更改文件的权限。menu_yaml_path就是应该从命令行传入的参数，如果是放在config/menu.yaml的话，应该在rails根目录下执行`wechat menu_create ./config/menu.yml`
