### ISSUE TITLE
location事件参数更新

### ISSUE THREAD

**Issue by jasper-fu** [Eric-Guo/wechat#64]
location事件参数列表变化，[当前代码](https://github.com/Eric-Guo/wechat/blob/master/lib/wechat/message.rb#L52)

参数变化可以参考：[微信开发文档](http://mp.weixin.qq.com/wiki/8/1b86529d05db9f960e48c3c7ca5be288.html)

**Comment by Eric-Guo** [comment]
更新了，能否帮忙测一下？

**Comment by jasper-fu** [comment]
测试过，正常工作，辛苦~

**Comment by jasper-fu** [comment]
BTW, 文档以及generator的部分没有更新 :P

**Comment by Eric-Guo** [comment]
已经更新，新的0.6.2也发布了。
