### ISSUE TITLE
Rails4.2不能bundle

### ISSUE THREAD

**Issue by csoop** [Eric-Guo/wechat#65]
如题Rails4.2bundle未成功。gemspec 改版本也没有bundle成功

**Comment by Eric-Guo** [comment]
`Gemfile`文件第一行改成[taobao源](https://ruby.taobao.org/)试试？

```
source 'https://ruby.taobao.org'
```

**Comment by csoop** [comment]
嗯嗯，ok了。bundle 成功了。但早上我有试过用taobao源啊 。哈哈，谢谢！
