### ISSUE TITLE
微信提示 UnSubscribe 返回内容不合法

### ISSUE THREAD

**Issue by IvanChou** [Eric-Guo/wechat#68]
微信公众平台报警提示 UnSubscribe 返回内容不合法
具体报错信息：

> Appid: wx*********6d63a
昵称: ***社区助手
时间: 2015-11-13 17:11:00
内容: 微信服务器向公众号推送消息或事件后，得到的回应不合法
次数: 5分钟 159次
错误样例: [OpenID=oAXFPt2m_VFQfnsrNX5DCqfzfOvs][Stamp=1447405860][3rdUrl10=http://***/api/weixin_mp/][Msg=Subscribe][Event=UnSubscribe][ip=***][response_length=234][response_content=<xml>
  <ToUserName>oAXFPt2m_VF*****CqfzfOvs</ToUserName>
  <FromUserName>gh_b66*****eb</FromUserName>
  <CreateTime>1447405860</CreateTime>
  <MsgType>text</MsgType>
  <Content>user can not receive this message</Content>
</xml>]
报警排查指引，请见: http://url.cn/ab0jnP

这个报错会在短时间大量退订的时候出现，应该是微信设置了容许少量错误返回

**Comment by Eric-Guo** [comment]
不是，这个报错的意思是就算你返回了消息，用户也收不到了（因为退订了）


所以如果你直接返回空字符串应该可以避免这个错误。

```ruby
class WechatsController < ApplicationController
  wechat_responder  
  # 当用户取消关注订阅
  on :event, with: 'unsubscribe' do |request|
    request.reply.text ""
  end
end
```

**Comment by IvanChou** [comment]
是的 这个问题并不会对我们的服务造成任何困扰，并且得益于它的报警我们可以在发完一次推送消息以后很快的发现是否有大量掉粉 😂😂😂😂

如果不写 `request.reply.text` 返回的应该也是空字串吧，这样做依然会有报错，周末我会试着排查一下，如果没有什么发现我就返回空字串试试，由于要大量掉粉才能触发，再现难度比较大

**Comment by Eric-Guo** [comment]
目前版本不能不写`request.reply.text`。我又仔细看了一下微信文档，[应该整个返回空](http://mp.weixin.qq.com/wiki/18/c66a9f0b5aa952346e46dc39de20f672.html)，让我再改改看。

**Comment by Eric-Guo** [comment]
v0.6.4已经修正，现在可以这样写，满足微信要求：

```ruby
class WechatsController < ApplicationController
  wechat_responder
  # 当用户取消关注订阅
  on :event, with: 'unsubscribe' do |request|
    request.reply.success # user can not receive this message
  end
end
```
