### ISSUE TITLE
生成二维码失败

### ISSUE THREAD

**Issue by bournewang** [Eric-Guo/wechat#71]
网站生成二维码时调用的API,如果token失效导致生成二维码失败，微信API返回json格式的错误信息时用的Content-Type是text/plain，程序只对application/json格式的返回做处理，导致无法自动刷新token、从而连续失败；

def parse_response(response, as)
      content_type = response.headers[:content_type]
      parse_as = {
        %r{^application\/json} => :json,
        %r{^text\/plain} => :json,  # 我加了这一行用以处理这个特例
        %r{^image\/.*} => :file
      }.each_with_object([]) { |match, memo| memo << match[1] if content_type =~ match[0] }.first || as || :text

**Comment by Eric-Guo** [comment]
不应该在这里处理，应该处理[48001](https://github.com/Eric-Guo/wechat/commit/0784319e1ebf93540a404aab217d675e10da3325)这个错误码，wechat 0.6.5刚刚发布，修正了这个错误，感谢报告。

**Comment by bournewang** [comment]
特例发生时，返回的errcod不是48001,而是40001, 内容如下：
----------------------------------------------------------------------------------
root@iZ23e9sw3l1Z:~/www/TimelineFrame# file public/wechat/64/IUhU3rCRxER3TrvwkA85SagmAa9_Z3-LS66l-zGn5DvcfH82gGkEHxY1AikylsIC.jpg 
public/wechat/64/IUhU3rCRxER3TrvwkA85SagmAa9_Z3-LS66l-zGn5DvcfH82gGkEHxY1AikylsIC.jpg: ASCII text, with no line terminators
root@iZ23e9sw3l1Z:~/www/TimelineFrame# cat public/wechat/64/IUhU3rCRxER3TrvwkA85SagmAa9_Z3-LS66l-zGn5DvcfH82gGkEHxY1AikylsIC.jpg 
{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest hint: [IN0835ent2]"}

**Comment by Eric-Guo** [comment]
也许微信服务器本身已经修掉了吧，反正现在应该没啥问题了。（同时处理48001/40001）

**Comment by bournewang** [comment]
应用中必然出现二维码获取失败的问题，

**Comment by Eric-Guo** [comment]
你是说还有最新的0.6.5版本这个问题？我看[你自己的fork](https://github.com/bournewang/wechat-rails)是半年前的，建议merge到最新版本再试试？
