### ISSUE TITLE
如何在controller里发送模板消息

### ISSUE THREAD

**Issue by skji** [Eric-Guo/wechat#72]
如题。可否提供个简单的示例。thanks

**Comment by skji** [comment]
刚用ruby 各种抓虾啊

**Comment by Eric-Guo** [comment]
公众号还是让@feitian124 回答比较好，我不怎么用公众号的模板消息。

**Comment by feitian124** [comment]
没用过模板消息.印象里面从前responder里面对这个没做支持, 可能要参照下面改改.
[template_message](https://github.com/Eric-Guo/wechat/blob/0784319e1ebf93540a404aab217d675e10da3325/bin/wechat#L395)

**Comment by skji** [comment]
已解决 谢谢两位！
```ruby
 Wechat.api.template_message_send Wechat::Message.to(openid).template(template)
```
