### ISSUE TITLE
使用jssdk会报Wechat::AccessTokenExpiredError的错

### ISSUE THREAD

**Issue by xuyao91** [Eric-Guo/wechat#73]
我在使用jssdk的时候，当token过期后，就会报Wechat::AccessTokenExpiredError的错误

**Comment by Eric-Guo** [comment]
报这个错正常的，按照设计应该触发[token refresh](https://github.com/Eric-Guo/wechat/blob/master/lib/wechat/api_base.rb#L40)，如果你遇到了没有触发token刷新的情况，是否是你直接使用了跳过with_access_token方法的原始RestClient对象？

**Comment by Eric-Guo** [comment]
至少可以确定wechat 0.6.6版本没有发生这个错误，这个issue暂时先关了。
