### ISSUE TITLE
on :scan, with: 'qrscene_xxxxxx'

### ISSUE THREAD

**Issue by kikyous** [Eric-Guo/wechat#84]
on :scan, with: 'qrscene_xxxxxx'

这里怎么匹配动态的qrscene_id, 支持吗? 写正则不起作用

**Comment by Eric-Guo** [comment]
这里有[例子](https://github.com/Eric-Guo/wechat/issues/55#issuecomment-145303582)

**Comment by kikyous** [comment]
动态的只能用 `on :event`匹配吗？

**Comment by Eric-Guo** [comment]
我想了1个多小时，还是决定不支持这个特性，的确用on :scan，支持正则更加符合直觉，但是倒霉的腾讯[底层协议](https://github.com/Eric-Guo/wechat/blob/871b9fd60fdfa43133cc5df603a6a4aecf9e4969/spec/lib/wechat/responder_spec.rb#L303-L319)，MsgType还是给我的event，甚至Event名字都没统一，现在的on :scan实现基于的是EventKey精确匹配，如果要支持正则，则需要在两个地方同时处理event事件，代码很难写，所以还是推荐写成on :event算了。
