### ISSUE TITLE
Command line mode 是不是只读取开发模式的配置？

### ISSUE THREAD

**Issue by kikyous** [Eric-Guo/wechat#85]
config/wechat.yml
里面设置的production配置不起作用

**Comment by Eric-Guo** [comment]
读取的是[default的配置](https://github.com/Eric-Guo/wechat/blob/d7b74e633818acbca16cb76cfc71f06def28f826/lib/wechat/api_loader.rb#L51)。

**Comment by kikyous** [comment]
应该根据 RAILS_ENV 来读取吧， 默认development

**Comment by Eric-Guo** [comment]
这样就是不得不在命令行方式下载入整个Rails栈，会导致命令行启动速度变慢，读default不会有这个问题。

**Comment by kikyous** [comment]
就使用ENV['RAILS_ENV']就行了，不用载入整个Rails栈

**Comment by Eric-Guo** [comment]
好主意，master已经这样了，需要发一个版本么？
