### ISSUE TITLE
Can not use helper like root_path inside on block

### ISSUE THREAD

**Issue by wongyouth** [Eric-Guo/wechat#9]
```
  # 默认的文字信息responder
  on :text do |request, content|
    request.reply.text "echo: #{content}" #Just echo
  end
```

I can not use `root_path` inside `on` block because it is in the Controller class scope not in the Controller instance scope. Why not inside a instance scope so we can use all the benefit from rails like rendering xml template with XmlBuilder, url helpers, etc.

**Comment by feitian124** [comment]
关注, 上下文的问题, 使用时确实碰到类似的不便.

**Comment by Eric-Guo** [comment]
#15 里面其实已经有这个修正了，但是似乎大规模merge的时候，漏了，现在已经在master branch上有了。
