### ISSUE TITLE
命令行工具如何拿到 config/wechat.yml 中的 ENV

### ISSUE THREAD

**Issue by ke-pan** [Eric-Guo/wechat#94]
我用的 dotenv 配置 ENV。运行命令行工具时拿不到 ENV。不知道推荐的做法是怎么样的？

**Comment by Eric-Guo** [comment]
如果你只有一个公众号，在用户目录下生成`~/.wechat.yml`，如果多个，或者希望和项目绑定，放在RAILS_ROOT/config/wechat.yml。可以在config/wechat.yml中应用环境变量，也可以使用[Figaro](https://github.com/goofansu/wechat-starter/blob/master/config/wechat.yml)

dotenv没有用过，应该和Figaro类似。

**Comment by ke-pan** [comment]
我就是在 RAILS_ROOT/config/wechat.yml 里设置的。发现用命令行工具的时候ENV还没有被设置，dotenv还没有把环境变量配置进去。Figaro 在用 wechat 命令行运行前载入了环境变量了吗？

**Comment by Eric-Guo** [comment]
应该是吧。。@goofansu 其实两个gem我都没用。。

**Comment by ke-pan** [comment]
我找到解决方案了，`dotenv wechat` 可以保证环境变量被设置。谢谢！

**Comment by Eric-Guo** [comment]
最好写一下解决方案，这样方便后来人。。

**Comment by goofansu** [comment]
如果你用rbenv的话，可以用插件https://github.com/rbenv/rbenv-vars。

设置环境变量只要在项目根目录建立`.rbenv-vars`，填入`KEY=VALUE`这样就行了。

**Comment by ke-pan** [comment]
我查看了一遍dotenv的文档，`Alternatively, you can use the dotenv executable to launch your application`, 就这样 `dotenv wechat` 就保证环境变量在wechat命令之前设置
