### ISSUE TITLE
不支持微信个性化菜单

### ISSUE THREAD

**Issue by danrtsey-wy** [Eric-Guo/wechat#95]
http://mp.weixin.qq.com/wiki/0/c48ccd12b69ae023159b4bfaa7c39c20.html
微信已经提供针对不同用户的个性化菜单，目前尚未支持

**Comment by Eric-Guo** [comment]
@wangyang0918 准备自己做么？这个功能？

**Comment by wangyang0918** [comment]
恩，打算自己做一个了

**Comment by Eric-Guo** [comment]
可以发PR啊，可以试试，我今晚准备弄weui-rails，如果看不到你的PR，明天我来做吧。

**Comment by wangyang0918** [comment]
最近刚熟悉rails和这个gem，还是大神你来吧，学习学习 @Eric-Guo

**Comment by Eric-Guo** [comment]
[0.7.6](https://rubygems.org/gems/wechat/versions/0.7.6)已经支持微信个性化菜单 。
