### ISSUE TITLE
求助“接口配置信息”

### ISSUE THREAD

**Issue by jimmy0017** [Eric-Guo/wechat#99]
微信要求：
URL
Token

实在找不到该填什么url。
token我知道是random gen一个即可。
url不确定要写啥？试过了root和/wechats都是错误。

**Comment by Eric-Guo** [comment]
URL就是你host的服务器地址，比如`http://your-server.com/wechat`

**Comment by dongli** [comment]
这个应该在readme里特别指出，因为这个是让新手最为挠头的地方。

**Comment by Eric-Guo** [comment]
@dongli 能帮忙提个PR改一下README么？

**Comment by jimmy0017** [comment]
@Eric-Guo @dongli 我提交了一个PR。不知道readme是否写的合乎规范。

**Comment by dongli** [comment]
@Eric-Guo 已经用上了这个gem，很好用。昨天自己折腾了一天，了解了整个流程，晚上花了一个小时换用`wechat` gem，实现同样的功能。@jimmy0017 你动作真快，我打算回家再提交个PR~

**Comment by jimmy0017** [comment]
@Eric-Guo 这个gem真的很棒。非常感谢。oauth也没用，但其他功能非常赞。
@dongli 因为邮件提醒，看到就搞了。加两行md挺快的。我加好了那行提醒。

**Comment by Eric-Guo** [comment]
@jimmy0017 谢谢，其实是前任 @skinnyworm 框架一开始就搭的好，当然，我也还算靠谱的维护者，oauth这块目前的处理其实也算有自己特色，决定单独写oauth的原因其实也是想和微信深度集成，而不是简单的做一个符合oauth2标准的认证（这个已经有(omniauth-wechat-oauth2)[https://github.com/skinnyworm/omniauth-wechat-oauth2]了）。
